// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: action_spray_rails.proto

package com.qhx.proto.event;

public interface ActionSprayRailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:qhx.proto.weve.ActionSprayRails)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 动作类型
   * </pre>
   *
   * <code>.qhx.proto.weve.ActionSprayRailsType action_type = 1;</code>
   * @return The enum numeric value on the wire for actionType.
   */
  int getActionTypeValue();
  /**
   * <pre>
   * 动作类型
   * </pre>
   *
   * <code>.qhx.proto.weve.ActionSprayRailsType action_type = 1;</code>
   * @return The actionType.
   */
  ActionSprayRailsType getActionType();

  /**
   * <pre>
   * 动作参数
   * </pre>
   *
   * <code>bytes options = 2;</code>
   * @return The options.
   */
  com.google.protobuf.ByteString getOptions();
}
