// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: action.proto

package com.qhx.proto.event;

public interface ActionSampleGPSStopOrBuilder extends
    // @@protoc_insertion_point(interface_extends:qhx.proto.weve.ActionSampleGPSStop)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uuid = 1;</code>
   * @return The uuid.
   */
  String getUuid();
  /**
   * <code>string uuid = 1;</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();
}
