// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spray_event.proto

package com.qhx.proto.event;

/**
 * <pre>
 * 相机设备所在的位置
 * </pre>
 *
 * Protobuf enum {@code qhx.proto.weve.event.spray.CameraPosition}
 */
public enum CameraPosition
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>CAMERA_POSITION_LEFT = 0;</code>
   */
  CAMERA_POSITION_LEFT(0),
  /**
   * <code>CAMERA_POSITION_MID = 1;</code>
   */
  CAMERA_POSITION_MID(1),
  /**
   * <code>CAMERA_POSITION_RIGHT = 2;</code>
   */
  CAMERA_POSITION_RIGHT(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>CAMERA_POSITION_LEFT = 0;</code>
   */
  public static final int CAMERA_POSITION_LEFT_VALUE = 0;
  /**
   * <code>CAMERA_POSITION_MID = 1;</code>
   */
  public static final int CAMERA_POSITION_MID_VALUE = 1;
  /**
   * <code>CAMERA_POSITION_RIGHT = 2;</code>
   */
  public static final int CAMERA_POSITION_RIGHT_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static CameraPosition valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static CameraPosition forNumber(int value) {
    switch (value) {
      case 0: return CAMERA_POSITION_LEFT;
      case 1: return CAMERA_POSITION_MID;
      case 2: return CAMERA_POSITION_RIGHT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<CameraPosition>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      CameraPosition> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<CameraPosition>() {
          public CameraPosition findValueByNumber(int number) {
            return CameraPosition.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return SprayEventOuterClass.getDescriptor().getEnumTypes().get(2);
  }

  private static final CameraPosition[] VALUES = values();

  public static CameraPosition valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private CameraPosition(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:qhx.proto.weve.event.spray.CameraPosition)
}

