// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: command.proto

package com.qhx.proto.event;

public final class CommandOuterClass {
  private CommandOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_qhx_proto_weve_Command_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_qhx_proto_weve_Command_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_qhx_proto_weve_CommandTaskDeploy_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_qhx_proto_weve_CommandTaskDeploy_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_qhx_proto_weve_CommandTaskInvokeAction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_qhx_proto_weve_CommandTaskInvokeAction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rcommand.proto\022\016qhx.proto.weve\032\ntask.pr" +
      "oto\"N\n\007Command\022\n\n\002id\030\001 \001(\t\022)\n\004type\030\002 \001(\016" +
      "2\033.qhx.proto.weve.CommandType\022\014\n\004body\030\003 " +
      "\001(\014\"7\n\021CommandTaskDeploy\022\"\n\004task\030\001 \001(\0132\024" +
      ".qhx.proto.weve.Task\"X\n\027CommandTaskInvok" +
      "eAction\022\017\n\007task_id\030\001 \001(\t\022\024\n\014action_index" +
      "\030\002 \001(\r\022\026\n\016action_options\030\003 \001(\014*\243\001\n\013Comma" +
      "ndType\022\030\n\024COMMAND_TYPE_UNKNOWN\020\000\022\026\n\022COMM" +
      "AND_TYPE_RESET\020\001\022\037\n\033COMMAND_TYPE_UPDATE_" +
      "REQUEST\020\002\022\034\n\030COMMAND_TYPE_TASK_DEPLOY\020\003\022" +
      "#\n\037COMMAND_TYPE_TASK_INVOKE_ACTION\020\004B\027\n\023" +
      "com.qhx.proto.eventP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          TaskOuterClass.getDescriptor(),
        });
    internal_static_qhx_proto_weve_Command_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_qhx_proto_weve_Command_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_qhx_proto_weve_Command_descriptor,
        new String[] { "Id", "Type", "Body", });
    internal_static_qhx_proto_weve_CommandTaskDeploy_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_qhx_proto_weve_CommandTaskDeploy_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_qhx_proto_weve_CommandTaskDeploy_descriptor,
        new String[] { "Task", });
    internal_static_qhx_proto_weve_CommandTaskInvokeAction_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_qhx_proto_weve_CommandTaskInvokeAction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_qhx_proto_weve_CommandTaskInvokeAction_descriptor,
        new String[] { "TaskId", "ActionIndex", "ActionOptions", });
    TaskOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
