// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: command.proto

package com.qhx.proto.event;

public interface CommandTaskInvokeActionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:qhx.proto.weve.CommandTaskInvokeAction)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 任务 Id
   * </pre>
   *
   * <code>string task_id = 1;</code>
   * @return The taskId.
   */
  String getTaskId();
  /**
   * <pre>
   * 任务 Id
   * </pre>
   *
   * <code>string task_id = 1;</code>
   * @return The bytes for taskId.
   */
  com.google.protobuf.ByteString
      getTaskIdBytes();

  /**
   * <pre>
   * 动作索引
   * </pre>
   *
   * <code>uint32 action_index = 2;</code>
   * @return The actionIndex.
   */
  int getActionIndex();

  /**
   * <pre>
   * 动作参数
   * </pre>
   *
   * <code>bytes action_options = 3;</code>
   * @return The actionOptions.
   */
  com.google.protobuf.ByteString getActionOptions();
}
