// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package com.qhx.proto.event;

/**
 * <pre>
 * 事件
 * </pre>
 *
 * Protobuf type {@code qhx.proto.weve.event.Event}
 */
public final class Event extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:qhx.proto.weve.event.Event)
    EventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Event.newBuilder() to construct.
  private Event(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Event() {
    severity_ = 0;
    source_ = 0;
    robotId_ = "";
    eventBody_ = com.google.protobuf.ByteString.EMPTY;
    message_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Event();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Event(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (timestamp_ != null) {
              subBuilder = timestamp_.toBuilder();
            }
            timestamp_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(timestamp_);
              timestamp_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            severity_ = rawValue;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            source_ = rawValue;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            robotId_ = s;
            break;
          }
          case 42: {

            eventBody_ = input.readBytes();
            break;
          }
          case 50: {
            String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          case 58: {
            EventContext.Builder subBuilder = null;
            if (context_ != null) {
              subBuilder = context_.toBuilder();
            }
            context_ = input.readMessage(EventContext.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(context_);
              context_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return EventOuterClass.internal_static_qhx_proto_weve_event_Event_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return EventOuterClass.internal_static_qhx_proto_weve_event_Event_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Event.class, Builder.class);
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 1;
  private com.google.protobuf.Timestamp timestamp_;
  /**
   * <pre>
   * 时间戳
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 1;</code>
   * @return Whether the timestamp field is set.
   */
  @Override
  public boolean hasTimestamp() {
    return timestamp_ != null;
  }
  /**
   * <pre>
   * 时间戳
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 1;</code>
   * @return The timestamp.
   */
  @Override
  public com.google.protobuf.Timestamp getTimestamp() {
    return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
  }
  /**
   * <pre>
   * 时间戳
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 1;</code>
   */
  @Override
  public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
    return getTimestamp();
  }

  public static final int SEVERITY_FIELD_NUMBER = 2;
  private int severity_;
  /**
   * <pre>
   * 严重程度
   * </pre>
   *
   * <code>.qhx.proto.weve.event.EventSeverity severity = 2;</code>
   * @return The enum numeric value on the wire for severity.
   */
  @Override public int getSeverityValue() {
    return severity_;
  }
  /**
   * <pre>
   * 严重程度
   * </pre>
   *
   * <code>.qhx.proto.weve.event.EventSeverity severity = 2;</code>
   * @return The severity.
   */
  @Override public EventSeverity getSeverity() {
    @SuppressWarnings("deprecation")
    EventSeverity result = EventSeverity.valueOf(severity_);
    return result == null ? EventSeverity.UNRECOGNIZED : result;
  }

  public static final int SOURCE_FIELD_NUMBER = 3;
  private int source_;
  /**
   * <pre>
   * 事件来源
   * </pre>
   *
   * <code>.qhx.proto.weve.event.EventSource source = 3;</code>
   * @return The enum numeric value on the wire for source.
   */
  @Override public int getSourceValue() {
    return source_;
  }
  /**
   * <pre>
   * 事件来源
   * </pre>
   *
   * <code>.qhx.proto.weve.event.EventSource source = 3;</code>
   * @return The source.
   */
  @Override public EventSource getSource() {
    @SuppressWarnings("deprecation")
    EventSource result = EventSource.valueOf(source_);
    return result == null ? EventSource.UNRECOGNIZED : result;
  }

  public static final int ROBOT_ID_FIELD_NUMBER = 4;
  private volatile Object robotId_;
  /**
   * <pre>
   * 机器人Id
   * </pre>
   *
   * <code>string robot_id = 4;</code>
   * @return The robotId.
   */
  @Override
  public String getRobotId() {
    Object ref = robotId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      robotId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 机器人Id
   * </pre>
   *
   * <code>string robot_id = 4;</code>
   * @return The bytes for robotId.
   */
  @Override
  public com.google.protobuf.ByteString
      getRobotIdBytes() {
    Object ref = robotId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      robotId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EVENT_BODY_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString eventBody_;
  /**
   * <pre>
   * 消息
   * </pre>
   *
   * <code>bytes event_body = 5;</code>
   * @return The eventBody.
   */
  @Override
  public com.google.protobuf.ByteString getEventBody() {
    return eventBody_;
  }

  public static final int MESSAGE_FIELD_NUMBER = 6;
  private volatile Object message_;
  /**
   * <pre>
   * 文本信息
   * </pre>
   *
   * <code>string message = 6;</code>
   * @return The message.
   */
  @Override
  public String getMessage() {
    Object ref = message_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 文本信息
   * </pre>
   *
   * <code>string message = 6;</code>
   * @return The bytes for message.
   */
  @Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    Object ref = message_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTEXT_FIELD_NUMBER = 7;
  private EventContext context_;
  /**
   * <pre>
   * 上下文
   * </pre>
   *
   * <code>.qhx.proto.weve.event.EventContext context = 7;</code>
   * @return Whether the context field is set.
   */
  @Override
  public boolean hasContext() {
    return context_ != null;
  }
  /**
   * <pre>
   * 上下文
   * </pre>
   *
   * <code>.qhx.proto.weve.event.EventContext context = 7;</code>
   * @return The context.
   */
  @Override
  public EventContext getContext() {
    return context_ == null ? EventContext.getDefaultInstance() : context_;
  }
  /**
   * <pre>
   * 上下文
   * </pre>
   *
   * <code>.qhx.proto.weve.event.EventContext context = 7;</code>
   */
  @Override
  public EventContextOrBuilder getContextOrBuilder() {
    return getContext();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (timestamp_ != null) {
      output.writeMessage(1, getTimestamp());
    }
    if (severity_ != EventSeverity.EVENT_SEVERITY_EMERGENCY.getNumber()) {
      output.writeEnum(2, severity_);
    }
    if (source_ != EventSource.EVENT_SOURCE_UNKNOWN.getNumber()) {
      output.writeEnum(3, source_);
    }
    if (!getRobotIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, robotId_);
    }
    if (!eventBody_.isEmpty()) {
      output.writeBytes(5, eventBody_);
    }
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, message_);
    }
    if (context_ != null) {
      output.writeMessage(7, getContext());
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (timestamp_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTimestamp());
    }
    if (severity_ != EventSeverity.EVENT_SEVERITY_EMERGENCY.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, severity_);
    }
    if (source_ != EventSource.EVENT_SOURCE_UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, source_);
    }
    if (!getRobotIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, robotId_);
    }
    if (!eventBody_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, eventBody_);
    }
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, message_);
    }
    if (context_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getContext());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Event)) {
      return super.equals(obj);
    }
    Event other = (Event) obj;

    if (hasTimestamp() != other.hasTimestamp()) return false;
    if (hasTimestamp()) {
      if (!getTimestamp()
          .equals(other.getTimestamp())) return false;
    }
    if (severity_ != other.severity_) return false;
    if (source_ != other.source_) return false;
    if (!getRobotId()
        .equals(other.getRobotId())) return false;
    if (!getEventBody()
        .equals(other.getEventBody())) return false;
    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (hasContext() != other.hasContext()) return false;
    if (hasContext()) {
      if (!getContext()
          .equals(other.getContext())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTimestamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
    }
    hash = (37 * hash) + SEVERITY_FIELD_NUMBER;
    hash = (53 * hash) + severity_;
    hash = (37 * hash) + SOURCE_FIELD_NUMBER;
    hash = (53 * hash) + source_;
    hash = (37 * hash) + ROBOT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRobotId().hashCode();
    hash = (37 * hash) + EVENT_BODY_FIELD_NUMBER;
    hash = (53 * hash) + getEventBody().hashCode();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    if (hasContext()) {
      hash = (37 * hash) + CONTEXT_FIELD_NUMBER;
      hash = (53 * hash) + getContext().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Event parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Event parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Event parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Event parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Event parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Event parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Event parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Event parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Event parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Event parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Event parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Event parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Event prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 事件
   * </pre>
   *
   * Protobuf type {@code qhx.proto.weve.event.Event}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:qhx.proto.weve.event.Event)
          EventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EventOuterClass.internal_static_qhx_proto_weve_event_Event_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EventOuterClass.internal_static_qhx_proto_weve_event_Event_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Event.class, Builder.class);
    }

    // Construct using com.qhx.proto.event.Event.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (timestampBuilder_ == null) {
        timestamp_ = null;
      } else {
        timestamp_ = null;
        timestampBuilder_ = null;
      }
      severity_ = 0;

      source_ = 0;

      robotId_ = "";

      eventBody_ = com.google.protobuf.ByteString.EMPTY;

      message_ = "";

      if (contextBuilder_ == null) {
        context_ = null;
      } else {
        context_ = null;
        contextBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return EventOuterClass.internal_static_qhx_proto_weve_event_Event_descriptor;
    }

    @Override
    public Event getDefaultInstanceForType() {
      return Event.getDefaultInstance();
    }

    @Override
    public Event build() {
      Event result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Event buildPartial() {
      Event result = new Event(this);
      if (timestampBuilder_ == null) {
        result.timestamp_ = timestamp_;
      } else {
        result.timestamp_ = timestampBuilder_.build();
      }
      result.severity_ = severity_;
      result.source_ = source_;
      result.robotId_ = robotId_;
      result.eventBody_ = eventBody_;
      result.message_ = message_;
      if (contextBuilder_ == null) {
        result.context_ = context_;
      } else {
        result.context_ = contextBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Event) {
        return mergeFrom((Event)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Event other) {
      if (other == Event.getDefaultInstance()) return this;
      if (other.hasTimestamp()) {
        mergeTimestamp(other.getTimestamp());
      }
      if (other.severity_ != 0) {
        setSeverityValue(other.getSeverityValue());
      }
      if (other.source_ != 0) {
        setSourceValue(other.getSourceValue());
      }
      if (!other.getRobotId().isEmpty()) {
        robotId_ = other.robotId_;
        onChanged();
      }
      if (other.getEventBody() != com.google.protobuf.ByteString.EMPTY) {
        setEventBody(other.getEventBody());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (other.hasContext()) {
        mergeContext(other.getContext());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Event parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Event) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.Timestamp timestamp_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
    /**
     * <pre>
     * 时间戳
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     * @return Whether the timestamp field is set.
     */
    public boolean hasTimestamp() {
      return timestampBuilder_ != null || timestamp_ != null;
    }
    /**
     * <pre>
     * 时间戳
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     * @return The timestamp.
     */
    public com.google.protobuf.Timestamp getTimestamp() {
      if (timestampBuilder_ == null) {
        return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      } else {
        return timestampBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 时间戳
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     */
    public Builder setTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timestamp_ = value;
        onChanged();
      } else {
        timestampBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 时间戳
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     */
    public Builder setTimestamp(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timestampBuilder_ == null) {
        timestamp_ = builderForValue.build();
        onChanged();
      } else {
        timestampBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 时间戳
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     */
    public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (timestamp_ != null) {
          timestamp_ =
            com.google.protobuf.Timestamp.newBuilder(timestamp_).mergeFrom(value).buildPartial();
        } else {
          timestamp_ = value;
        }
        onChanged();
      } else {
        timestampBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 时间戳
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     */
    public Builder clearTimestamp() {
      if (timestampBuilder_ == null) {
        timestamp_ = null;
        onChanged();
      } else {
        timestamp_ = null;
        timestampBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 时间戳
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     */
    public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
      
      onChanged();
      return getTimestampFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 时间戳
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      if (timestampBuilder_ != null) {
        return timestampBuilder_.getMessageOrBuilder();
      } else {
        return timestamp_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      }
    }
    /**
     * <pre>
     * 时间戳
     * </pre>
     *
     * <code>.google.protobuf.Timestamp timestamp = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getTimestampFieldBuilder() {
      if (timestampBuilder_ == null) {
        timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getTimestamp(),
                getParentForChildren(),
                isClean());
        timestamp_ = null;
      }
      return timestampBuilder_;
    }

    private int severity_ = 0;
    /**
     * <pre>
     * 严重程度
     * </pre>
     *
     * <code>.qhx.proto.weve.event.EventSeverity severity = 2;</code>
     * @return The enum numeric value on the wire for severity.
     */
    @Override public int getSeverityValue() {
      return severity_;
    }
    /**
     * <pre>
     * 严重程度
     * </pre>
     *
     * <code>.qhx.proto.weve.event.EventSeverity severity = 2;</code>
     * @param value The enum numeric value on the wire for severity to set.
     * @return This builder for chaining.
     */
    public Builder setSeverityValue(int value) {
      
      severity_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 严重程度
     * </pre>
     *
     * <code>.qhx.proto.weve.event.EventSeverity severity = 2;</code>
     * @return The severity.
     */
    @Override
    public EventSeverity getSeverity() {
      @SuppressWarnings("deprecation")
      EventSeverity result = EventSeverity.valueOf(severity_);
      return result == null ? EventSeverity.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 严重程度
     * </pre>
     *
     * <code>.qhx.proto.weve.event.EventSeverity severity = 2;</code>
     * @param value The severity to set.
     * @return This builder for chaining.
     */
    public Builder setSeverity(EventSeverity value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      severity_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 严重程度
     * </pre>
     *
     * <code>.qhx.proto.weve.event.EventSeverity severity = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeverity() {
      
      severity_ = 0;
      onChanged();
      return this;
    }

    private int source_ = 0;
    /**
     * <pre>
     * 事件来源
     * </pre>
     *
     * <code>.qhx.proto.weve.event.EventSource source = 3;</code>
     * @return The enum numeric value on the wire for source.
     */
    @Override public int getSourceValue() {
      return source_;
    }
    /**
     * <pre>
     * 事件来源
     * </pre>
     *
     * <code>.qhx.proto.weve.event.EventSource source = 3;</code>
     * @param value The enum numeric value on the wire for source to set.
     * @return This builder for chaining.
     */
    public Builder setSourceValue(int value) {
      
      source_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 事件来源
     * </pre>
     *
     * <code>.qhx.proto.weve.event.EventSource source = 3;</code>
     * @return The source.
     */
    @Override
    public EventSource getSource() {
      @SuppressWarnings("deprecation")
      EventSource result = EventSource.valueOf(source_);
      return result == null ? EventSource.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 事件来源
     * </pre>
     *
     * <code>.qhx.proto.weve.event.EventSource source = 3;</code>
     * @param value The source to set.
     * @return This builder for chaining.
     */
    public Builder setSource(EventSource value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      source_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 事件来源
     * </pre>
     *
     * <code>.qhx.proto.weve.event.EventSource source = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSource() {
      
      source_ = 0;
      onChanged();
      return this;
    }

    private Object robotId_ = "";
    /**
     * <pre>
     * 机器人Id
     * </pre>
     *
     * <code>string robot_id = 4;</code>
     * @return The robotId.
     */
    public String getRobotId() {
      Object ref = robotId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        robotId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 机器人Id
     * </pre>
     *
     * <code>string robot_id = 4;</code>
     * @return The bytes for robotId.
     */
    public com.google.protobuf.ByteString
        getRobotIdBytes() {
      Object ref = robotId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        robotId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 机器人Id
     * </pre>
     *
     * <code>string robot_id = 4;</code>
     * @param value The robotId to set.
     * @return This builder for chaining.
     */
    public Builder setRobotId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      robotId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 机器人Id
     * </pre>
     *
     * <code>string robot_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRobotId() {
      
      robotId_ = getDefaultInstance().getRobotId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 机器人Id
     * </pre>
     *
     * <code>string robot_id = 4;</code>
     * @param value The bytes for robotId to set.
     * @return This builder for chaining.
     */
    public Builder setRobotIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      robotId_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString eventBody_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * 消息
     * </pre>
     *
     * <code>bytes event_body = 5;</code>
     * @return The eventBody.
     */
    @Override
    public com.google.protobuf.ByteString getEventBody() {
      return eventBody_;
    }
    /**
     * <pre>
     * 消息
     * </pre>
     *
     * <code>bytes event_body = 5;</code>
     * @param value The eventBody to set.
     * @return This builder for chaining.
     */
    public Builder setEventBody(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      eventBody_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息
     * </pre>
     *
     * <code>bytes event_body = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventBody() {
      
      eventBody_ = getDefaultInstance().getEventBody();
      onChanged();
      return this;
    }

    private Object message_ = "";
    /**
     * <pre>
     * 文本信息
     * </pre>
     *
     * <code>string message = 6;</code>
     * @return The message.
     */
    public String getMessage() {
      Object ref = message_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 文本信息
     * </pre>
     *
     * <code>string message = 6;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 文本信息
     * </pre>
     *
     * <code>string message = 6;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 文本信息
     * </pre>
     *
     * <code>string message = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 文本信息
     * </pre>
     *
     * <code>string message = 6;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private EventContext context_;
    private com.google.protobuf.SingleFieldBuilderV3<
            EventContext, EventContext.Builder, EventContextOrBuilder> contextBuilder_;
    /**
     * <pre>
     * 上下文
     * </pre>
     *
     * <code>.qhx.proto.weve.event.EventContext context = 7;</code>
     * @return Whether the context field is set.
     */
    public boolean hasContext() {
      return contextBuilder_ != null || context_ != null;
    }
    /**
     * <pre>
     * 上下文
     * </pre>
     *
     * <code>.qhx.proto.weve.event.EventContext context = 7;</code>
     * @return The context.
     */
    public EventContext getContext() {
      if (contextBuilder_ == null) {
        return context_ == null ? EventContext.getDefaultInstance() : context_;
      } else {
        return contextBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 上下文
     * </pre>
     *
     * <code>.qhx.proto.weve.event.EventContext context = 7;</code>
     */
    public Builder setContext(EventContext value) {
      if (contextBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        context_ = value;
        onChanged();
      } else {
        contextBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 上下文
     * </pre>
     *
     * <code>.qhx.proto.weve.event.EventContext context = 7;</code>
     */
    public Builder setContext(
        EventContext.Builder builderForValue) {
      if (contextBuilder_ == null) {
        context_ = builderForValue.build();
        onChanged();
      } else {
        contextBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 上下文
     * </pre>
     *
     * <code>.qhx.proto.weve.event.EventContext context = 7;</code>
     */
    public Builder mergeContext(EventContext value) {
      if (contextBuilder_ == null) {
        if (context_ != null) {
          context_ =
            EventContext.newBuilder(context_).mergeFrom(value).buildPartial();
        } else {
          context_ = value;
        }
        onChanged();
      } else {
        contextBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 上下文
     * </pre>
     *
     * <code>.qhx.proto.weve.event.EventContext context = 7;</code>
     */
    public Builder clearContext() {
      if (contextBuilder_ == null) {
        context_ = null;
        onChanged();
      } else {
        context_ = null;
        contextBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 上下文
     * </pre>
     *
     * <code>.qhx.proto.weve.event.EventContext context = 7;</code>
     */
    public EventContext.Builder getContextBuilder() {
      
      onChanged();
      return getContextFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 上下文
     * </pre>
     *
     * <code>.qhx.proto.weve.event.EventContext context = 7;</code>
     */
    public EventContextOrBuilder getContextOrBuilder() {
      if (contextBuilder_ != null) {
        return contextBuilder_.getMessageOrBuilder();
      } else {
        return context_ == null ?
            EventContext.getDefaultInstance() : context_;
      }
    }
    /**
     * <pre>
     * 上下文
     * </pre>
     *
     * <code>.qhx.proto.weve.event.EventContext context = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            EventContext, EventContext.Builder, EventContextOrBuilder>
        getContextFieldBuilder() {
      if (contextBuilder_ == null) {
        contextBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                EventContext, EventContext.Builder, EventContextOrBuilder>(
                getContext(),
                getParentForChildren(),
                isClean());
        context_ = null;
      }
      return contextBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:qhx.proto.weve.event.Event)
  }

  // @@protoc_insertion_point(class_scope:qhx.proto.weve.event.Event)
  private static final Event DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Event();
  }

  public static Event getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Event>
      PARSER = new com.google.protobuf.AbstractParser<Event>() {
    @Override
    public Event parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Event(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Event> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Event> getParserForType() {
    return PARSER;
  }

  @Override
  public Event getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

