// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geo.proto

package com.qhx.proto.event;

/**
 * <pre>
 * 参考系
 * </pre>
 *
 * Protobuf type {@code qhx.proto.weve.Frame}
 */
public final class Frame extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:qhx.proto.weve.Frame)
    FrameOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Frame.newBuilder() to construct.
  private Frame(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Frame() {
    mapId_ = "";
    frameType_ = 0;
    frameRef_ = 0;
    altitudeRef_ = 0;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Frame();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Frame(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            index_ = input.readUInt32();
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            mapId_ = s;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            frameType_ = rawValue;
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            frameRef_ = rawValue;
            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            altitudeRef_ = rawValue;
            break;
          }
          case 50: {
            Pose.Builder subBuilder = null;
            if (refPose_ != null) {
              subBuilder = refPose_.toBuilder();
            }
            refPose_ = input.readMessage(Pose.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(refPose_);
              refPose_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Geo.internal_static_qhx_proto_weve_Frame_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Geo.internal_static_qhx_proto_weve_Frame_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Frame.class, Builder.class);
  }

  public static final int INDEX_FIELD_NUMBER = 1;
  private int index_;
  /**
   * <pre>
   * 索引
   * </pre>
   *
   * <code>uint32 index = 1;</code>
   * @return The index.
   */
  @Override
  public int getIndex() {
    return index_;
  }

  public static final int MAP_ID_FIELD_NUMBER = 2;
  private volatile Object mapId_;
  /**
   * <pre>
   * 地图Id
   * </pre>
   *
   * <code>string map_id = 2;</code>
   * @return The mapId.
   */
  @Override
  public String getMapId() {
    Object ref = mapId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      mapId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 地图Id
   * </pre>
   *
   * <code>string map_id = 2;</code>
   * @return The bytes for mapId.
   */
  @Override
  public com.google.protobuf.ByteString
      getMapIdBytes() {
    Object ref = mapId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      mapId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FRAME_TYPE_FIELD_NUMBER = 3;
  private int frameType_;
  /**
   * <pre>
   * 参考系类型
   * </pre>
   *
   * <code>.qhx.proto.weve.FrameType frame_type = 3;</code>
   * @return The enum numeric value on the wire for frameType.
   */
  @Override public int getFrameTypeValue() {
    return frameType_;
  }
  /**
   * <pre>
   * 参考系类型
   * </pre>
   *
   * <code>.qhx.proto.weve.FrameType frame_type = 3;</code>
   * @return The frameType.
   */
  @Override public FrameType getFrameType() {
    @SuppressWarnings("deprecation")
    FrameType result = FrameType.valueOf(frameType_);
    return result == null ? FrameType.UNRECOGNIZED : result;
  }

  public static final int FRAME_REF_FIELD_NUMBER = 4;
  private int frameRef_;
  /**
   * <pre>
   * 参考基准
   * 若参考系类型为`FRAME_TYPE_REF_`前缀，则需要设置此项，否则可不设置或按照如下设置：
   * ECEF坐标对应`FRAME_REF_EARTH_CENTER`，经纬度坐标对应`FRAME_REF_EARTH_GEODETIC_DATUM`
   * </pre>
   *
   * <code>.qhx.proto.weve.FrameRef frame_ref = 4;</code>
   * @return The enum numeric value on the wire for frameRef.
   */
  @Override public int getFrameRefValue() {
    return frameRef_;
  }
  /**
   * <pre>
   * 参考基准
   * 若参考系类型为`FRAME_TYPE_REF_`前缀，则需要设置此项，否则可不设置或按照如下设置：
   * ECEF坐标对应`FRAME_REF_EARTH_CENTER`，经纬度坐标对应`FRAME_REF_EARTH_GEODETIC_DATUM`
   * </pre>
   *
   * <code>.qhx.proto.weve.FrameRef frame_ref = 4;</code>
   * @return The frameRef.
   */
  @Override public FrameRef getFrameRef() {
    @SuppressWarnings("deprecation")
    FrameRef result = FrameRef.valueOf(frameRef_);
    return result == null ? FrameRef.UNRECOGNIZED : result;
  }

  public static final int ALTITUDE_REF_FIELD_NUMBER = 5;
  private int altitudeRef_;
  /**
   * <pre>
   * 高度参考基准
   * 此设置仅在经纬度坐标系中有意义，在笛卡尔坐标系中一般以±z轴为高
   * </pre>
   *
   * <code>.qhx.proto.weve.FrameRef altitude_ref = 5;</code>
   * @return The enum numeric value on the wire for altitudeRef.
   */
  @Override public int getAltitudeRefValue() {
    return altitudeRef_;
  }
  /**
   * <pre>
   * 高度参考基准
   * 此设置仅在经纬度坐标系中有意义，在笛卡尔坐标系中一般以±z轴为高
   * </pre>
   *
   * <code>.qhx.proto.weve.FrameRef altitude_ref = 5;</code>
   * @return The altitudeRef.
   */
  @Override public FrameRef getAltitudeRef() {
    @SuppressWarnings("deprecation")
    FrameRef result = FrameRef.valueOf(altitudeRef_);
    return result == null ? FrameRef.UNRECOGNIZED : result;
  }

  public static final int REF_POSE_FIELD_NUMBER = 6;
  private Pose refPose_;
  /**
   * <pre>
   * 自定义参考位姿
   * 若参考系类型为`FRAME_TYPE_REF_`前缀，且参考基准为`FRAME_REF_POSE`时，则需要设置此项
   * 可表示当前参考系在其父参考系中的位姿，例如当前ENU参考系的原点在WGS84的经纬度坐标
   * </pre>
   *
   * <code>.qhx.proto.weve.Pose ref_pose = 6;</code>
   * @return Whether the refPose field is set.
   */
  @Override
  public boolean hasRefPose() {
    return refPose_ != null;
  }
  /**
   * <pre>
   * 自定义参考位姿
   * 若参考系类型为`FRAME_TYPE_REF_`前缀，且参考基准为`FRAME_REF_POSE`时，则需要设置此项
   * 可表示当前参考系在其父参考系中的位姿，例如当前ENU参考系的原点在WGS84的经纬度坐标
   * </pre>
   *
   * <code>.qhx.proto.weve.Pose ref_pose = 6;</code>
   * @return The refPose.
   */
  @Override
  public Pose getRefPose() {
    return refPose_ == null ? Pose.getDefaultInstance() : refPose_;
  }
  /**
   * <pre>
   * 自定义参考位姿
   * 若参考系类型为`FRAME_TYPE_REF_`前缀，且参考基准为`FRAME_REF_POSE`时，则需要设置此项
   * 可表示当前参考系在其父参考系中的位姿，例如当前ENU参考系的原点在WGS84的经纬度坐标
   * </pre>
   *
   * <code>.qhx.proto.weve.Pose ref_pose = 6;</code>
   */
  @Override
  public PoseOrBuilder getRefPoseOrBuilder() {
    return getRefPose();
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (index_ != 0) {
      output.writeUInt32(1, index_);
    }
    if (!getMapIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, mapId_);
    }
    if (frameType_ != FrameType.FRAME_TYPE_UNKNOWN.getNumber()) {
      output.writeEnum(3, frameType_);
    }
    if (frameRef_ != FrameRef.FRAME_REF_UNKNOWN.getNumber()) {
      output.writeEnum(4, frameRef_);
    }
    if (altitudeRef_ != FrameRef.FRAME_REF_UNKNOWN.getNumber()) {
      output.writeEnum(5, altitudeRef_);
    }
    if (refPose_ != null) {
      output.writeMessage(6, getRefPose());
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (index_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, index_);
    }
    if (!getMapIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, mapId_);
    }
    if (frameType_ != FrameType.FRAME_TYPE_UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, frameType_);
    }
    if (frameRef_ != FrameRef.FRAME_REF_UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, frameRef_);
    }
    if (altitudeRef_ != FrameRef.FRAME_REF_UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, altitudeRef_);
    }
    if (refPose_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getRefPose());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Frame)) {
      return super.equals(obj);
    }
    Frame other = (Frame) obj;

    if (getIndex()
        != other.getIndex()) return false;
    if (!getMapId()
        .equals(other.getMapId())) return false;
    if (frameType_ != other.frameType_) return false;
    if (frameRef_ != other.frameRef_) return false;
    if (altitudeRef_ != other.altitudeRef_) return false;
    if (hasRefPose() != other.hasRefPose()) return false;
    if (hasRefPose()) {
      if (!getRefPose()
          .equals(other.getRefPose())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + INDEX_FIELD_NUMBER;
    hash = (53 * hash) + getIndex();
    hash = (37 * hash) + MAP_ID_FIELD_NUMBER;
    hash = (53 * hash) + getMapId().hashCode();
    hash = (37 * hash) + FRAME_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + frameType_;
    hash = (37 * hash) + FRAME_REF_FIELD_NUMBER;
    hash = (53 * hash) + frameRef_;
    hash = (37 * hash) + ALTITUDE_REF_FIELD_NUMBER;
    hash = (53 * hash) + altitudeRef_;
    if (hasRefPose()) {
      hash = (37 * hash) + REF_POSE_FIELD_NUMBER;
      hash = (53 * hash) + getRefPose().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Frame parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Frame parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Frame parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Frame parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Frame parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Frame parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Frame parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Frame parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Frame parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Frame parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Frame parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Frame parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Frame prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 参考系
   * </pre>
   *
   * Protobuf type {@code qhx.proto.weve.Frame}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:qhx.proto.weve.Frame)
          FrameOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Geo.internal_static_qhx_proto_weve_Frame_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Geo.internal_static_qhx_proto_weve_Frame_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Frame.class, Builder.class);
    }

    // Construct using com.qhx.proto.event.Frame.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      index_ = 0;

      mapId_ = "";

      frameType_ = 0;

      frameRef_ = 0;

      altitudeRef_ = 0;

      if (refPoseBuilder_ == null) {
        refPose_ = null;
      } else {
        refPose_ = null;
        refPoseBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Geo.internal_static_qhx_proto_weve_Frame_descriptor;
    }

    @Override
    public Frame getDefaultInstanceForType() {
      return Frame.getDefaultInstance();
    }

    @Override
    public Frame build() {
      Frame result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Frame buildPartial() {
      Frame result = new Frame(this);
      result.index_ = index_;
      result.mapId_ = mapId_;
      result.frameType_ = frameType_;
      result.frameRef_ = frameRef_;
      result.altitudeRef_ = altitudeRef_;
      if (refPoseBuilder_ == null) {
        result.refPose_ = refPose_;
      } else {
        result.refPose_ = refPoseBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Frame) {
        return mergeFrom((Frame)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Frame other) {
      if (other == Frame.getDefaultInstance()) return this;
      if (other.getIndex() != 0) {
        setIndex(other.getIndex());
      }
      if (!other.getMapId().isEmpty()) {
        mapId_ = other.mapId_;
        onChanged();
      }
      if (other.frameType_ != 0) {
        setFrameTypeValue(other.getFrameTypeValue());
      }
      if (other.frameRef_ != 0) {
        setFrameRefValue(other.getFrameRefValue());
      }
      if (other.altitudeRef_ != 0) {
        setAltitudeRefValue(other.getAltitudeRefValue());
      }
      if (other.hasRefPose()) {
        mergeRefPose(other.getRefPose());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Frame parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Frame) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int index_ ;
    /**
     * <pre>
     * 索引
     * </pre>
     *
     * <code>uint32 index = 1;</code>
     * @return The index.
     */
    @Override
    public int getIndex() {
      return index_;
    }
    /**
     * <pre>
     * 索引
     * </pre>
     *
     * <code>uint32 index = 1;</code>
     * @param value The index to set.
     * @return This builder for chaining.
     */
    public Builder setIndex(int value) {
      
      index_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 索引
     * </pre>
     *
     * <code>uint32 index = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIndex() {
      
      index_ = 0;
      onChanged();
      return this;
    }

    private Object mapId_ = "";
    /**
     * <pre>
     * 地图Id
     * </pre>
     *
     * <code>string map_id = 2;</code>
     * @return The mapId.
     */
    public String getMapId() {
      Object ref = mapId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        mapId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 地图Id
     * </pre>
     *
     * <code>string map_id = 2;</code>
     * @return The bytes for mapId.
     */
    public com.google.protobuf.ByteString
        getMapIdBytes() {
      Object ref = mapId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        mapId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 地图Id
     * </pre>
     *
     * <code>string map_id = 2;</code>
     * @param value The mapId to set.
     * @return This builder for chaining.
     */
    public Builder setMapId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mapId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 地图Id
     * </pre>
     *
     * <code>string map_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMapId() {
      
      mapId_ = getDefaultInstance().getMapId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 地图Id
     * </pre>
     *
     * <code>string map_id = 2;</code>
     * @param value The bytes for mapId to set.
     * @return This builder for chaining.
     */
    public Builder setMapIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mapId_ = value;
      onChanged();
      return this;
    }

    private int frameType_ = 0;
    /**
     * <pre>
     * 参考系类型
     * </pre>
     *
     * <code>.qhx.proto.weve.FrameType frame_type = 3;</code>
     * @return The enum numeric value on the wire for frameType.
     */
    @Override public int getFrameTypeValue() {
      return frameType_;
    }
    /**
     * <pre>
     * 参考系类型
     * </pre>
     *
     * <code>.qhx.proto.weve.FrameType frame_type = 3;</code>
     * @param value The enum numeric value on the wire for frameType to set.
     * @return This builder for chaining.
     */
    public Builder setFrameTypeValue(int value) {
      
      frameType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 参考系类型
     * </pre>
     *
     * <code>.qhx.proto.weve.FrameType frame_type = 3;</code>
     * @return The frameType.
     */
    @Override
    public FrameType getFrameType() {
      @SuppressWarnings("deprecation")
      FrameType result = FrameType.valueOf(frameType_);
      return result == null ? FrameType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 参考系类型
     * </pre>
     *
     * <code>.qhx.proto.weve.FrameType frame_type = 3;</code>
     * @param value The frameType to set.
     * @return This builder for chaining.
     */
    public Builder setFrameType(FrameType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      frameType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 参考系类型
     * </pre>
     *
     * <code>.qhx.proto.weve.FrameType frame_type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFrameType() {
      
      frameType_ = 0;
      onChanged();
      return this;
    }

    private int frameRef_ = 0;
    /**
     * <pre>
     * 参考基准
     * 若参考系类型为`FRAME_TYPE_REF_`前缀，则需要设置此项，否则可不设置或按照如下设置：
     * ECEF坐标对应`FRAME_REF_EARTH_CENTER`，经纬度坐标对应`FRAME_REF_EARTH_GEODETIC_DATUM`
     * </pre>
     *
     * <code>.qhx.proto.weve.FrameRef frame_ref = 4;</code>
     * @return The enum numeric value on the wire for frameRef.
     */
    @Override public int getFrameRefValue() {
      return frameRef_;
    }
    /**
     * <pre>
     * 参考基准
     * 若参考系类型为`FRAME_TYPE_REF_`前缀，则需要设置此项，否则可不设置或按照如下设置：
     * ECEF坐标对应`FRAME_REF_EARTH_CENTER`，经纬度坐标对应`FRAME_REF_EARTH_GEODETIC_DATUM`
     * </pre>
     *
     * <code>.qhx.proto.weve.FrameRef frame_ref = 4;</code>
     * @param value The enum numeric value on the wire for frameRef to set.
     * @return This builder for chaining.
     */
    public Builder setFrameRefValue(int value) {
      
      frameRef_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 参考基准
     * 若参考系类型为`FRAME_TYPE_REF_`前缀，则需要设置此项，否则可不设置或按照如下设置：
     * ECEF坐标对应`FRAME_REF_EARTH_CENTER`，经纬度坐标对应`FRAME_REF_EARTH_GEODETIC_DATUM`
     * </pre>
     *
     * <code>.qhx.proto.weve.FrameRef frame_ref = 4;</code>
     * @return The frameRef.
     */
    @Override
    public FrameRef getFrameRef() {
      @SuppressWarnings("deprecation")
      FrameRef result = FrameRef.valueOf(frameRef_);
      return result == null ? FrameRef.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 参考基准
     * 若参考系类型为`FRAME_TYPE_REF_`前缀，则需要设置此项，否则可不设置或按照如下设置：
     * ECEF坐标对应`FRAME_REF_EARTH_CENTER`，经纬度坐标对应`FRAME_REF_EARTH_GEODETIC_DATUM`
     * </pre>
     *
     * <code>.qhx.proto.weve.FrameRef frame_ref = 4;</code>
     * @param value The frameRef to set.
     * @return This builder for chaining.
     */
    public Builder setFrameRef(FrameRef value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      frameRef_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 参考基准
     * 若参考系类型为`FRAME_TYPE_REF_`前缀，则需要设置此项，否则可不设置或按照如下设置：
     * ECEF坐标对应`FRAME_REF_EARTH_CENTER`，经纬度坐标对应`FRAME_REF_EARTH_GEODETIC_DATUM`
     * </pre>
     *
     * <code>.qhx.proto.weve.FrameRef frame_ref = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearFrameRef() {
      
      frameRef_ = 0;
      onChanged();
      return this;
    }

    private int altitudeRef_ = 0;
    /**
     * <pre>
     * 高度参考基准
     * 此设置仅在经纬度坐标系中有意义，在笛卡尔坐标系中一般以±z轴为高
     * </pre>
     *
     * <code>.qhx.proto.weve.FrameRef altitude_ref = 5;</code>
     * @return The enum numeric value on the wire for altitudeRef.
     */
    @Override public int getAltitudeRefValue() {
      return altitudeRef_;
    }
    /**
     * <pre>
     * 高度参考基准
     * 此设置仅在经纬度坐标系中有意义，在笛卡尔坐标系中一般以±z轴为高
     * </pre>
     *
     * <code>.qhx.proto.weve.FrameRef altitude_ref = 5;</code>
     * @param value The enum numeric value on the wire for altitudeRef to set.
     * @return This builder for chaining.
     */
    public Builder setAltitudeRefValue(int value) {
      
      altitudeRef_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 高度参考基准
     * 此设置仅在经纬度坐标系中有意义，在笛卡尔坐标系中一般以±z轴为高
     * </pre>
     *
     * <code>.qhx.proto.weve.FrameRef altitude_ref = 5;</code>
     * @return The altitudeRef.
     */
    @Override
    public FrameRef getAltitudeRef() {
      @SuppressWarnings("deprecation")
      FrameRef result = FrameRef.valueOf(altitudeRef_);
      return result == null ? FrameRef.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 高度参考基准
     * 此设置仅在经纬度坐标系中有意义，在笛卡尔坐标系中一般以±z轴为高
     * </pre>
     *
     * <code>.qhx.proto.weve.FrameRef altitude_ref = 5;</code>
     * @param value The altitudeRef to set.
     * @return This builder for chaining.
     */
    public Builder setAltitudeRef(FrameRef value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      altitudeRef_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 高度参考基准
     * 此设置仅在经纬度坐标系中有意义，在笛卡尔坐标系中一般以±z轴为高
     * </pre>
     *
     * <code>.qhx.proto.weve.FrameRef altitude_ref = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAltitudeRef() {
      
      altitudeRef_ = 0;
      onChanged();
      return this;
    }

    private Pose refPose_;
    private com.google.protobuf.SingleFieldBuilderV3<
            Pose, Pose.Builder, PoseOrBuilder> refPoseBuilder_;
    /**
     * <pre>
     * 自定义参考位姿
     * 若参考系类型为`FRAME_TYPE_REF_`前缀，且参考基准为`FRAME_REF_POSE`时，则需要设置此项
     * 可表示当前参考系在其父参考系中的位姿，例如当前ENU参考系的原点在WGS84的经纬度坐标
     * </pre>
     *
     * <code>.qhx.proto.weve.Pose ref_pose = 6;</code>
     * @return Whether the refPose field is set.
     */
    public boolean hasRefPose() {
      return refPoseBuilder_ != null || refPose_ != null;
    }
    /**
     * <pre>
     * 自定义参考位姿
     * 若参考系类型为`FRAME_TYPE_REF_`前缀，且参考基准为`FRAME_REF_POSE`时，则需要设置此项
     * 可表示当前参考系在其父参考系中的位姿，例如当前ENU参考系的原点在WGS84的经纬度坐标
     * </pre>
     *
     * <code>.qhx.proto.weve.Pose ref_pose = 6;</code>
     * @return The refPose.
     */
    public Pose getRefPose() {
      if (refPoseBuilder_ == null) {
        return refPose_ == null ? Pose.getDefaultInstance() : refPose_;
      } else {
        return refPoseBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 自定义参考位姿
     * 若参考系类型为`FRAME_TYPE_REF_`前缀，且参考基准为`FRAME_REF_POSE`时，则需要设置此项
     * 可表示当前参考系在其父参考系中的位姿，例如当前ENU参考系的原点在WGS84的经纬度坐标
     * </pre>
     *
     * <code>.qhx.proto.weve.Pose ref_pose = 6;</code>
     */
    public Builder setRefPose(Pose value) {
      if (refPoseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        refPose_ = value;
        onChanged();
      } else {
        refPoseBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 自定义参考位姿
     * 若参考系类型为`FRAME_TYPE_REF_`前缀，且参考基准为`FRAME_REF_POSE`时，则需要设置此项
     * 可表示当前参考系在其父参考系中的位姿，例如当前ENU参考系的原点在WGS84的经纬度坐标
     * </pre>
     *
     * <code>.qhx.proto.weve.Pose ref_pose = 6;</code>
     */
    public Builder setRefPose(
        Pose.Builder builderForValue) {
      if (refPoseBuilder_ == null) {
        refPose_ = builderForValue.build();
        onChanged();
      } else {
        refPoseBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 自定义参考位姿
     * 若参考系类型为`FRAME_TYPE_REF_`前缀，且参考基准为`FRAME_REF_POSE`时，则需要设置此项
     * 可表示当前参考系在其父参考系中的位姿，例如当前ENU参考系的原点在WGS84的经纬度坐标
     * </pre>
     *
     * <code>.qhx.proto.weve.Pose ref_pose = 6;</code>
     */
    public Builder mergeRefPose(Pose value) {
      if (refPoseBuilder_ == null) {
        if (refPose_ != null) {
          refPose_ =
            Pose.newBuilder(refPose_).mergeFrom(value).buildPartial();
        } else {
          refPose_ = value;
        }
        onChanged();
      } else {
        refPoseBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 自定义参考位姿
     * 若参考系类型为`FRAME_TYPE_REF_`前缀，且参考基准为`FRAME_REF_POSE`时，则需要设置此项
     * 可表示当前参考系在其父参考系中的位姿，例如当前ENU参考系的原点在WGS84的经纬度坐标
     * </pre>
     *
     * <code>.qhx.proto.weve.Pose ref_pose = 6;</code>
     */
    public Builder clearRefPose() {
      if (refPoseBuilder_ == null) {
        refPose_ = null;
        onChanged();
      } else {
        refPose_ = null;
        refPoseBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 自定义参考位姿
     * 若参考系类型为`FRAME_TYPE_REF_`前缀，且参考基准为`FRAME_REF_POSE`时，则需要设置此项
     * 可表示当前参考系在其父参考系中的位姿，例如当前ENU参考系的原点在WGS84的经纬度坐标
     * </pre>
     *
     * <code>.qhx.proto.weve.Pose ref_pose = 6;</code>
     */
    public Pose.Builder getRefPoseBuilder() {
      
      onChanged();
      return getRefPoseFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 自定义参考位姿
     * 若参考系类型为`FRAME_TYPE_REF_`前缀，且参考基准为`FRAME_REF_POSE`时，则需要设置此项
     * 可表示当前参考系在其父参考系中的位姿，例如当前ENU参考系的原点在WGS84的经纬度坐标
     * </pre>
     *
     * <code>.qhx.proto.weve.Pose ref_pose = 6;</code>
     */
    public PoseOrBuilder getRefPoseOrBuilder() {
      if (refPoseBuilder_ != null) {
        return refPoseBuilder_.getMessageOrBuilder();
      } else {
        return refPose_ == null ?
            Pose.getDefaultInstance() : refPose_;
      }
    }
    /**
     * <pre>
     * 自定义参考位姿
     * 若参考系类型为`FRAME_TYPE_REF_`前缀，且参考基准为`FRAME_REF_POSE`时，则需要设置此项
     * 可表示当前参考系在其父参考系中的位姿，例如当前ENU参考系的原点在WGS84的经纬度坐标
     * </pre>
     *
     * <code>.qhx.proto.weve.Pose ref_pose = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            Pose, Pose.Builder, PoseOrBuilder>
        getRefPoseFieldBuilder() {
      if (refPoseBuilder_ == null) {
        refPoseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                Pose, Pose.Builder, PoseOrBuilder>(
                getRefPose(),
                getParentForChildren(),
                isClean());
        refPose_ = null;
      }
      return refPoseBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:qhx.proto.weve.Frame)
  }

  // @@protoc_insertion_point(class_scope:qhx.proto.weve.Frame)
  private static final Frame DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Frame();
  }

  public static Frame getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Frame>
      PARSER = new com.google.protobuf.AbstractParser<Frame>() {
    @Override
    public Frame parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Frame(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Frame> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Frame> getParserForType() {
    return PARSER;
  }

  @Override
  public Frame getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

