// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gte_message.proto

package com.qhx.proto.event;

/**
 * Protobuf type {@code qhx.proto.weve.gte.GteMessageTest}
 */
public final class GteMessageTest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:qhx.proto.weve.gte.GteMessageTest)
    GteMessageTestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GteMessageTest.newBuilder() to construct.
  private GteMessageTest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GteMessageTest() {
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new GteMessageTest();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GteMessageTest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            seq_ = input.readUInt32();
            break;
          }
          case 16: {

            halTimestamp_ = input.readUInt32();
            break;
          }
          case 24: {

            dwtTimestamp_ = input.readUInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return GteMessageOuterClass.internal_static_qhx_proto_weve_gte_GteMessageTest_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return GteMessageOuterClass.internal_static_qhx_proto_weve_gte_GteMessageTest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            GteMessageTest.class, Builder.class);
  }

  public static final int SEQ_FIELD_NUMBER = 1;
  private int seq_;
  /**
   * <code>uint32 seq = 1;</code>
   * @return The seq.
   */
  @Override
  public int getSeq() {
    return seq_;
  }

  public static final int HAL_TIMESTAMP_FIELD_NUMBER = 2;
  private int halTimestamp_;
  /**
   * <code>uint32 hal_timestamp = 2;</code>
   * @return The halTimestamp.
   */
  @Override
  public int getHalTimestamp() {
    return halTimestamp_;
  }

  public static final int DWT_TIMESTAMP_FIELD_NUMBER = 3;
  private int dwtTimestamp_;
  /**
   * <code>uint32 dwt_timestamp = 3;</code>
   * @return The dwtTimestamp.
   */
  @Override
  public int getDwtTimestamp() {
    return dwtTimestamp_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (seq_ != 0) {
      output.writeUInt32(1, seq_);
    }
    if (halTimestamp_ != 0) {
      output.writeUInt32(2, halTimestamp_);
    }
    if (dwtTimestamp_ != 0) {
      output.writeUInt32(3, dwtTimestamp_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (seq_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, seq_);
    }
    if (halTimestamp_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, halTimestamp_);
    }
    if (dwtTimestamp_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, dwtTimestamp_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof GteMessageTest)) {
      return super.equals(obj);
    }
    GteMessageTest other = (GteMessageTest) obj;

    if (getSeq()
        != other.getSeq()) return false;
    if (getHalTimestamp()
        != other.getHalTimestamp()) return false;
    if (getDwtTimestamp()
        != other.getDwtTimestamp()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SEQ_FIELD_NUMBER;
    hash = (53 * hash) + getSeq();
    hash = (37 * hash) + HAL_TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + getHalTimestamp();
    hash = (37 * hash) + DWT_TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + getDwtTimestamp();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static GteMessageTest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GteMessageTest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GteMessageTest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GteMessageTest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GteMessageTest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GteMessageTest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GteMessageTest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GteMessageTest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static GteMessageTest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static GteMessageTest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static GteMessageTest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GteMessageTest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(GteMessageTest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code qhx.proto.weve.gte.GteMessageTest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:qhx.proto.weve.gte.GteMessageTest)
          GteMessageTestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GteMessageOuterClass.internal_static_qhx_proto_weve_gte_GteMessageTest_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GteMessageOuterClass.internal_static_qhx_proto_weve_gte_GteMessageTest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GteMessageTest.class, Builder.class);
    }

    // Construct using com.qhx.proto.event.GteMessageTest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      seq_ = 0;

      halTimestamp_ = 0;

      dwtTimestamp_ = 0;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return GteMessageOuterClass.internal_static_qhx_proto_weve_gte_GteMessageTest_descriptor;
    }

    @Override
    public GteMessageTest getDefaultInstanceForType() {
      return GteMessageTest.getDefaultInstance();
    }

    @Override
    public GteMessageTest build() {
      GteMessageTest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public GteMessageTest buildPartial() {
      GteMessageTest result = new GteMessageTest(this);
      result.seq_ = seq_;
      result.halTimestamp_ = halTimestamp_;
      result.dwtTimestamp_ = dwtTimestamp_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof GteMessageTest) {
        return mergeFrom((GteMessageTest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(GteMessageTest other) {
      if (other == GteMessageTest.getDefaultInstance()) return this;
      if (other.getSeq() != 0) {
        setSeq(other.getSeq());
      }
      if (other.getHalTimestamp() != 0) {
        setHalTimestamp(other.getHalTimestamp());
      }
      if (other.getDwtTimestamp() != 0) {
        setDwtTimestamp(other.getDwtTimestamp());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      GteMessageTest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (GteMessageTest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int seq_ ;
    /**
     * <code>uint32 seq = 1;</code>
     * @return The seq.
     */
    @Override
    public int getSeq() {
      return seq_;
    }
    /**
     * <code>uint32 seq = 1;</code>
     * @param value The seq to set.
     * @return This builder for chaining.
     */
    public Builder setSeq(int value) {
      
      seq_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 seq = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSeq() {
      
      seq_ = 0;
      onChanged();
      return this;
    }

    private int halTimestamp_ ;
    /**
     * <code>uint32 hal_timestamp = 2;</code>
     * @return The halTimestamp.
     */
    @Override
    public int getHalTimestamp() {
      return halTimestamp_;
    }
    /**
     * <code>uint32 hal_timestamp = 2;</code>
     * @param value The halTimestamp to set.
     * @return This builder for chaining.
     */
    public Builder setHalTimestamp(int value) {
      
      halTimestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 hal_timestamp = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearHalTimestamp() {
      
      halTimestamp_ = 0;
      onChanged();
      return this;
    }

    private int dwtTimestamp_ ;
    /**
     * <code>uint32 dwt_timestamp = 3;</code>
     * @return The dwtTimestamp.
     */
    @Override
    public int getDwtTimestamp() {
      return dwtTimestamp_;
    }
    /**
     * <code>uint32 dwt_timestamp = 3;</code>
     * @param value The dwtTimestamp to set.
     * @return This builder for chaining.
     */
    public Builder setDwtTimestamp(int value) {
      
      dwtTimestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 dwt_timestamp = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDwtTimestamp() {
      
      dwtTimestamp_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:qhx.proto.weve.gte.GteMessageTest)
  }

  // @@protoc_insertion_point(class_scope:qhx.proto.weve.gte.GteMessageTest)
  private static final GteMessageTest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new GteMessageTest();
  }

  public static GteMessageTest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GteMessageTest>
      PARSER = new com.google.protobuf.AbstractParser<GteMessageTest>() {
    @Override
    public GteMessageTest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GteMessageTest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GteMessageTest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<GteMessageTest> getParserForType() {
    return PARSER;
  }

  @Override
  public GteMessageTest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

