// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gte_message_sc.proto

package com.qhx.proto.event;

public final class GteMessageSc {
  private GteMessageSc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_qhx_proto_weve_gte_ScRtkStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_qhx_proto_weve_gte_ScRtkStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_qhx_proto_weve_gte_ScWifiStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_qhx_proto_weve_gte_ScWifiStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_qhx_proto_weve_gte_ScStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_qhx_proto_weve_gte_ScStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024gte_message_sc.proto\022\022qhx.proto.weve.g" +
      "te\"G\n\013ScRtkStatus\0228\n\nant_status\030\001 \001(\0162$." +
      "qhx.proto.weve.gte.RtkAntennaStatus\"g\n\014S" +
      "cWifiStatus\022A\n\013ap_ant_mode\030\001 \001(\0162,.qhx.p" +
      "roto.weve.gte.ScWifiAntennaControlMode\022\024" +
      "\n\014ap_ant_angle\030\002 \001(\002\"\357\001\n\010ScStatus\022:\n\020lif" +
      "t_status_left\030\001 \001(\0162 .qhx.proto.weve.gte" +
      ".ScLiftStatus\022;\n\021lift_status_right\030\002 \001(\016" +
      "2 .qhx.proto.weve.gte.ScLiftStatus\0225\n\013wi" +
      "fi_status\030\003 \001(\0132 .qhx.proto.weve.gte.ScW" +
      "ifiStatus\0223\n\nrtk_status\030\004 \001(\0132\037.qhx.prot" +
      "o.weve.gte.ScRtkStatus*\305\001\n\020RtkAntennaSta" +
      "tus\022\036\n\032RTK_ANTENNA_STATUS_UNKNOWN\020\000\022\031\n\025R" +
      "TK_ANTENNA_STATUS_UP\020\001\022\033\n\027RTK_ANTENNA_ST" +
      "ATUS_DOWN\020\002\022\035\n\031RTK_ANTENNA_STATUS_MOVING" +
      "\020\003\022\034\n\030RTK_ANTENNA_STATUS_ERROR\020\004\022\034\n\030RTK_" +
      "ANTENNA_STATUS_RESET\020\005*\245\001\n\030ScWifiAntenna" +
      "ControlMode\022 \n\034SC_WIFI_ANTENNA_MODE_UNKN" +
      "OWN\020\000\022\035\n\031SC_WIFI_ANTENNA_MODE_AUTO\020\001\022#\n\037" +
      "SC_WIFI_ANTENNA_MODE_MANUAL_ABS\020\002\022#\n\037SC_" +
      "WIFI_ANTENNA_MODE_MANUAL_REL\020\003*\302\001\n\014ScLif" +
      "tStatus\022\032\n\026SC_LIFT_STATUS_UNKNOWN\020\000\022\025\n\021S" +
      "C_LIFT_STATUS_UP\020\001\022\027\n\023SC_LIFT_STATUS_DOW" +
      "N\020\002\022\027\n\023SC_LIFT_STATUS_STOP\020\003\022\031\n\025SC_LIFT_" +
      "STATUS_MOVING\020\004\022\030\n\024SC_LIFT_STATUS_ERROR\020" +
      "\005\022\030\n\024SC_LIFT_STATUS_RESET\020\006B\027\n\023com.qhx.p" +
      "roto.eventP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_qhx_proto_weve_gte_ScRtkStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_qhx_proto_weve_gte_ScRtkStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_qhx_proto_weve_gte_ScRtkStatus_descriptor,
        new String[] { "AntStatus", });
    internal_static_qhx_proto_weve_gte_ScWifiStatus_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_qhx_proto_weve_gte_ScWifiStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_qhx_proto_weve_gte_ScWifiStatus_descriptor,
        new String[] { "ApAntMode", "ApAntAngle", });
    internal_static_qhx_proto_weve_gte_ScStatus_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_qhx_proto_weve_gte_ScStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_qhx_proto_weve_gte_ScStatus_descriptor,
        new String[] { "LiftStatusLeft", "LiftStatusRight", "WifiStatus", "RtkStatus", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
