// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event_nav.proto

package com.qhx.proto.event;

/**
 * Protobuf type {@code qhx.proto.weve.event.odometry.NavEventRobotStatus}
 */
public final class NavEventRobotStatus extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:qhx.proto.weve.event.odometry.NavEventRobotStatus)
    NavEventRobotStatusOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NavEventRobotStatus.newBuilder() to construct.
  private NavEventRobotStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NavEventRobotStatus() {
    ctrlMode_ = 0;
    poseType_ = 0;
    motionStatus_ = 0;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new NavEventRobotStatus();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NavEventRobotStatus(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            ctrlMode_ = rawValue;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            poseType_ = rawValue;
            break;
          }
          case 29: {

            velX_ = input.readFloat();
            break;
          }
          case 37: {

            velY_ = input.readFloat();
            break;
          }
          case 45: {

            angularVel_ = input.readFloat();
            break;
          }
          case 48: {
            int rawValue = input.readEnum();

            motionStatus_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return EventNav.internal_static_qhx_proto_weve_event_odometry_NavEventRobotStatus_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return EventNav.internal_static_qhx_proto_weve_event_odometry_NavEventRobotStatus_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            NavEventRobotStatus.class, Builder.class);
  }

  public static final int CTRL_MODE_FIELD_NUMBER = 1;
  private int ctrlMode_;
  /**
   * <code>.qhx.proto.weve.event.odometry.NavEventControlMode ctrl_mode = 1;</code>
   * @return The enum numeric value on the wire for ctrlMode.
   */
  @Override public int getCtrlModeValue() {
    return ctrlMode_;
  }
  /**
   * <code>.qhx.proto.weve.event.odometry.NavEventControlMode ctrl_mode = 1;</code>
   * @return The ctrlMode.
   */
  @Override public NavEventControlMode getCtrlMode() {
    @SuppressWarnings("deprecation")
    NavEventControlMode result = NavEventControlMode.valueOf(ctrlMode_);
    return result == null ? NavEventControlMode.UNRECOGNIZED : result;
  }

  public static final int POSE_TYPE_FIELD_NUMBER = 2;
  private int poseType_;
  /**
   * <code>.qhx.proto.weve.event.odometry.NavEventPoseType pose_type = 2;</code>
   * @return The enum numeric value on the wire for poseType.
   */
  @Override public int getPoseTypeValue() {
    return poseType_;
  }
  /**
   * <code>.qhx.proto.weve.event.odometry.NavEventPoseType pose_type = 2;</code>
   * @return The poseType.
   */
  @Override public NavEventPoseType getPoseType() {
    @SuppressWarnings("deprecation")
    NavEventPoseType result = NavEventPoseType.valueOf(poseType_);
    return result == null ? NavEventPoseType.UNRECOGNIZED : result;
  }

  public static final int VEL_X_FIELD_NUMBER = 3;
  private float velX_;
  /**
   * <code>float vel_x = 3;</code>
   * @return The velX.
   */
  @Override
  public float getVelX() {
    return velX_;
  }

  public static final int VEL_Y_FIELD_NUMBER = 4;
  private float velY_;
  /**
   * <code>float vel_y = 4;</code>
   * @return The velY.
   */
  @Override
  public float getVelY() {
    return velY_;
  }

  public static final int ANGULAR_VEL_FIELD_NUMBER = 5;
  private float angularVel_;
  /**
   * <code>float angular_vel = 5;</code>
   * @return The angularVel.
   */
  @Override
  public float getAngularVel() {
    return angularVel_;
  }

  public static final int MOTION_STATUS_FIELD_NUMBER = 6;
  private int motionStatus_;
  /**
   * <code>.qhx.proto.weve.event.odometry.NavEvenMotionStatus motion_status = 6;</code>
   * @return The enum numeric value on the wire for motionStatus.
   */
  @Override public int getMotionStatusValue() {
    return motionStatus_;
  }
  /**
   * <code>.qhx.proto.weve.event.odometry.NavEvenMotionStatus motion_status = 6;</code>
   * @return The motionStatus.
   */
  @Override public NavEvenMotionStatus getMotionStatus() {
    @SuppressWarnings("deprecation")
    NavEvenMotionStatus result = NavEvenMotionStatus.valueOf(motionStatus_);
    return result == null ? NavEvenMotionStatus.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (ctrlMode_ != NavEventControlMode.CONTROL_MODE_UNKNOWN.getNumber()) {
      output.writeEnum(1, ctrlMode_);
    }
    if (poseType_ != NavEventPoseType.POSE_TYPE_UNKNOWN.getNumber()) {
      output.writeEnum(2, poseType_);
    }
    if (velX_ != 0F) {
      output.writeFloat(3, velX_);
    }
    if (velY_ != 0F) {
      output.writeFloat(4, velY_);
    }
    if (angularVel_ != 0F) {
      output.writeFloat(5, angularVel_);
    }
    if (motionStatus_ != NavEvenMotionStatus.MOTION_STATUS_UNKNOWN.getNumber()) {
      output.writeEnum(6, motionStatus_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (ctrlMode_ != NavEventControlMode.CONTROL_MODE_UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, ctrlMode_);
    }
    if (poseType_ != NavEventPoseType.POSE_TYPE_UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, poseType_);
    }
    if (velX_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, velX_);
    }
    if (velY_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(4, velY_);
    }
    if (angularVel_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(5, angularVel_);
    }
    if (motionStatus_ != NavEvenMotionStatus.MOTION_STATUS_UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, motionStatus_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof NavEventRobotStatus)) {
      return super.equals(obj);
    }
    NavEventRobotStatus other = (NavEventRobotStatus) obj;

    if (ctrlMode_ != other.ctrlMode_) return false;
    if (poseType_ != other.poseType_) return false;
    if (Float.floatToIntBits(getVelX())
        != Float.floatToIntBits(
            other.getVelX())) return false;
    if (Float.floatToIntBits(getVelY())
        != Float.floatToIntBits(
            other.getVelY())) return false;
    if (Float.floatToIntBits(getAngularVel())
        != Float.floatToIntBits(
            other.getAngularVel())) return false;
    if (motionStatus_ != other.motionStatus_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CTRL_MODE_FIELD_NUMBER;
    hash = (53 * hash) + ctrlMode_;
    hash = (37 * hash) + POSE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + poseType_;
    hash = (37 * hash) + VEL_X_FIELD_NUMBER;
    hash = (53 * hash) + Float.floatToIntBits(
        getVelX());
    hash = (37 * hash) + VEL_Y_FIELD_NUMBER;
    hash = (53 * hash) + Float.floatToIntBits(
        getVelY());
    hash = (37 * hash) + ANGULAR_VEL_FIELD_NUMBER;
    hash = (53 * hash) + Float.floatToIntBits(
        getAngularVel());
    hash = (37 * hash) + MOTION_STATUS_FIELD_NUMBER;
    hash = (53 * hash) + motionStatus_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static NavEventRobotStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NavEventRobotStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NavEventRobotStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NavEventRobotStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NavEventRobotStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NavEventRobotStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NavEventRobotStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static NavEventRobotStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static NavEventRobotStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static NavEventRobotStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static NavEventRobotStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static NavEventRobotStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(NavEventRobotStatus prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code qhx.proto.weve.event.odometry.NavEventRobotStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:qhx.proto.weve.event.odometry.NavEventRobotStatus)
          NavEventRobotStatusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EventNav.internal_static_qhx_proto_weve_event_odometry_NavEventRobotStatus_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EventNav.internal_static_qhx_proto_weve_event_odometry_NavEventRobotStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NavEventRobotStatus.class, Builder.class);
    }

    // Construct using com.qhx.proto.event.NavEventRobotStatus.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      ctrlMode_ = 0;

      poseType_ = 0;

      velX_ = 0F;

      velY_ = 0F;

      angularVel_ = 0F;

      motionStatus_ = 0;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return EventNav.internal_static_qhx_proto_weve_event_odometry_NavEventRobotStatus_descriptor;
    }

    @Override
    public NavEventRobotStatus getDefaultInstanceForType() {
      return NavEventRobotStatus.getDefaultInstance();
    }

    @Override
    public NavEventRobotStatus build() {
      NavEventRobotStatus result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public NavEventRobotStatus buildPartial() {
      NavEventRobotStatus result = new NavEventRobotStatus(this);
      result.ctrlMode_ = ctrlMode_;
      result.poseType_ = poseType_;
      result.velX_ = velX_;
      result.velY_ = velY_;
      result.angularVel_ = angularVel_;
      result.motionStatus_ = motionStatus_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof NavEventRobotStatus) {
        return mergeFrom((NavEventRobotStatus)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(NavEventRobotStatus other) {
      if (other == NavEventRobotStatus.getDefaultInstance()) return this;
      if (other.ctrlMode_ != 0) {
        setCtrlModeValue(other.getCtrlModeValue());
      }
      if (other.poseType_ != 0) {
        setPoseTypeValue(other.getPoseTypeValue());
      }
      if (other.getVelX() != 0F) {
        setVelX(other.getVelX());
      }
      if (other.getVelY() != 0F) {
        setVelY(other.getVelY());
      }
      if (other.getAngularVel() != 0F) {
        setAngularVel(other.getAngularVel());
      }
      if (other.motionStatus_ != 0) {
        setMotionStatusValue(other.getMotionStatusValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      NavEventRobotStatus parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (NavEventRobotStatus) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int ctrlMode_ = 0;
    /**
     * <code>.qhx.proto.weve.event.odometry.NavEventControlMode ctrl_mode = 1;</code>
     * @return The enum numeric value on the wire for ctrlMode.
     */
    @Override public int getCtrlModeValue() {
      return ctrlMode_;
    }
    /**
     * <code>.qhx.proto.weve.event.odometry.NavEventControlMode ctrl_mode = 1;</code>
     * @param value The enum numeric value on the wire for ctrlMode to set.
     * @return This builder for chaining.
     */
    public Builder setCtrlModeValue(int value) {
      
      ctrlMode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.qhx.proto.weve.event.odometry.NavEventControlMode ctrl_mode = 1;</code>
     * @return The ctrlMode.
     */
    @Override
    public NavEventControlMode getCtrlMode() {
      @SuppressWarnings("deprecation")
      NavEventControlMode result = NavEventControlMode.valueOf(ctrlMode_);
      return result == null ? NavEventControlMode.UNRECOGNIZED : result;
    }
    /**
     * <code>.qhx.proto.weve.event.odometry.NavEventControlMode ctrl_mode = 1;</code>
     * @param value The ctrlMode to set.
     * @return This builder for chaining.
     */
    public Builder setCtrlMode(NavEventControlMode value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      ctrlMode_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.qhx.proto.weve.event.odometry.NavEventControlMode ctrl_mode = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCtrlMode() {
      
      ctrlMode_ = 0;
      onChanged();
      return this;
    }

    private int poseType_ = 0;
    /**
     * <code>.qhx.proto.weve.event.odometry.NavEventPoseType pose_type = 2;</code>
     * @return The enum numeric value on the wire for poseType.
     */
    @Override public int getPoseTypeValue() {
      return poseType_;
    }
    /**
     * <code>.qhx.proto.weve.event.odometry.NavEventPoseType pose_type = 2;</code>
     * @param value The enum numeric value on the wire for poseType to set.
     * @return This builder for chaining.
     */
    public Builder setPoseTypeValue(int value) {
      
      poseType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.qhx.proto.weve.event.odometry.NavEventPoseType pose_type = 2;</code>
     * @return The poseType.
     */
    @Override
    public NavEventPoseType getPoseType() {
      @SuppressWarnings("deprecation")
      NavEventPoseType result = NavEventPoseType.valueOf(poseType_);
      return result == null ? NavEventPoseType.UNRECOGNIZED : result;
    }
    /**
     * <code>.qhx.proto.weve.event.odometry.NavEventPoseType pose_type = 2;</code>
     * @param value The poseType to set.
     * @return This builder for chaining.
     */
    public Builder setPoseType(NavEventPoseType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      poseType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.qhx.proto.weve.event.odometry.NavEventPoseType pose_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPoseType() {
      
      poseType_ = 0;
      onChanged();
      return this;
    }

    private float velX_ ;
    /**
     * <code>float vel_x = 3;</code>
     * @return The velX.
     */
    @Override
    public float getVelX() {
      return velX_;
    }
    /**
     * <code>float vel_x = 3;</code>
     * @param value The velX to set.
     * @return This builder for chaining.
     */
    public Builder setVelX(float value) {
      
      velX_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float vel_x = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearVelX() {
      
      velX_ = 0F;
      onChanged();
      return this;
    }

    private float velY_ ;
    /**
     * <code>float vel_y = 4;</code>
     * @return The velY.
     */
    @Override
    public float getVelY() {
      return velY_;
    }
    /**
     * <code>float vel_y = 4;</code>
     * @param value The velY to set.
     * @return This builder for chaining.
     */
    public Builder setVelY(float value) {
      
      velY_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float vel_y = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearVelY() {
      
      velY_ = 0F;
      onChanged();
      return this;
    }

    private float angularVel_ ;
    /**
     * <code>float angular_vel = 5;</code>
     * @return The angularVel.
     */
    @Override
    public float getAngularVel() {
      return angularVel_;
    }
    /**
     * <code>float angular_vel = 5;</code>
     * @param value The angularVel to set.
     * @return This builder for chaining.
     */
    public Builder setAngularVel(float value) {
      
      angularVel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float angular_vel = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAngularVel() {
      
      angularVel_ = 0F;
      onChanged();
      return this;
    }

    private int motionStatus_ = 0;
    /**
     * <code>.qhx.proto.weve.event.odometry.NavEvenMotionStatus motion_status = 6;</code>
     * @return The enum numeric value on the wire for motionStatus.
     */
    @Override public int getMotionStatusValue() {
      return motionStatus_;
    }
    /**
     * <code>.qhx.proto.weve.event.odometry.NavEvenMotionStatus motion_status = 6;</code>
     * @param value The enum numeric value on the wire for motionStatus to set.
     * @return This builder for chaining.
     */
    public Builder setMotionStatusValue(int value) {
      
      motionStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.qhx.proto.weve.event.odometry.NavEvenMotionStatus motion_status = 6;</code>
     * @return The motionStatus.
     */
    @Override
    public NavEvenMotionStatus getMotionStatus() {
      @SuppressWarnings("deprecation")
      NavEvenMotionStatus result = NavEvenMotionStatus.valueOf(motionStatus_);
      return result == null ? NavEvenMotionStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.qhx.proto.weve.event.odometry.NavEvenMotionStatus motion_status = 6;</code>
     * @param value The motionStatus to set.
     * @return This builder for chaining.
     */
    public Builder setMotionStatus(NavEvenMotionStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      motionStatus_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.qhx.proto.weve.event.odometry.NavEvenMotionStatus motion_status = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMotionStatus() {
      
      motionStatus_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:qhx.proto.weve.event.odometry.NavEventRobotStatus)
  }

  // @@protoc_insertion_point(class_scope:qhx.proto.weve.event.odometry.NavEventRobotStatus)
  private static final NavEventRobotStatus DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new NavEventRobotStatus();
  }

  public static NavEventRobotStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NavEventRobotStatus>
      PARSER = new com.google.protobuf.AbstractParser<NavEventRobotStatus>() {
    @Override
    public NavEventRobotStatus parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NavEventRobotStatus(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NavEventRobotStatus> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<NavEventRobotStatus> getParserForType() {
    return PARSER;
  }

  @Override
  public NavEventRobotStatus getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

