// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event_nav.proto

package com.qhx.proto.event;

/**
 * Protobuf type {@code qhx.proto.weve.event.odometry.NavEventSensorOnlineStatus}
 */
public final class NavEventSensorOnlineStatus extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:qhx.proto.weve.event.odometry.NavEventSensorOnlineStatus)
    NavEventSensorOnlineStatusOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NavEventSensorOnlineStatus.newBuilder() to construct.
  private NavEventSensorOnlineStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NavEventSensorOnlineStatus() {
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new NavEventSensorOnlineStatus();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NavEventSensorOnlineStatus(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            sprayCam1Online_ = input.readBool();
            break;
          }
          case 16: {

            sprayCam2Online_ = input.readBool();
            break;
          }
          case 24: {

            sprayCam3Online_ = input.readBool();
            break;
          }
          case 32: {

            navCam1Online_ = input.readBool();
            break;
          }
          case 40: {

            navCam2Online_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return EventNav.internal_static_qhx_proto_weve_event_odometry_NavEventSensorOnlineStatus_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return EventNav.internal_static_qhx_proto_weve_event_odometry_NavEventSensorOnlineStatus_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            NavEventSensorOnlineStatus.class, Builder.class);
  }

  public static final int SPRAY_CAM1_ONLINE_FIELD_NUMBER = 1;
  private boolean sprayCam1Online_;
  /**
   * <code>bool spray_cam1_online = 1;</code>
   * @return The sprayCam1Online.
   */
  @Override
  public boolean getSprayCam1Online() {
    return sprayCam1Online_;
  }

  public static final int SPRAY_CAM2_ONLINE_FIELD_NUMBER = 2;
  private boolean sprayCam2Online_;
  /**
   * <code>bool spray_cam2_online = 2;</code>
   * @return The sprayCam2Online.
   */
  @Override
  public boolean getSprayCam2Online() {
    return sprayCam2Online_;
  }

  public static final int SPRAY_CAM3_ONLINE_FIELD_NUMBER = 3;
  private boolean sprayCam3Online_;
  /**
   * <code>bool spray_cam3_online = 3;</code>
   * @return The sprayCam3Online.
   */
  @Override
  public boolean getSprayCam3Online() {
    return sprayCam3Online_;
  }

  public static final int NAV_CAM1_ONLINE_FIELD_NUMBER = 4;
  private boolean navCam1Online_;
  /**
   * <code>bool nav_cam1_online = 4;</code>
   * @return The navCam1Online.
   */
  @Override
  public boolean getNavCam1Online() {
    return navCam1Online_;
  }

  public static final int NAV_CAM2_ONLINE_FIELD_NUMBER = 5;
  private boolean navCam2Online_;
  /**
   * <code>bool nav_cam2_online = 5;</code>
   * @return The navCam2Online.
   */
  @Override
  public boolean getNavCam2Online() {
    return navCam2Online_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (sprayCam1Online_ != false) {
      output.writeBool(1, sprayCam1Online_);
    }
    if (sprayCam2Online_ != false) {
      output.writeBool(2, sprayCam2Online_);
    }
    if (sprayCam3Online_ != false) {
      output.writeBool(3, sprayCam3Online_);
    }
    if (navCam1Online_ != false) {
      output.writeBool(4, navCam1Online_);
    }
    if (navCam2Online_ != false) {
      output.writeBool(5, navCam2Online_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (sprayCam1Online_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, sprayCam1Online_);
    }
    if (sprayCam2Online_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, sprayCam2Online_);
    }
    if (sprayCam3Online_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, sprayCam3Online_);
    }
    if (navCam1Online_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, navCam1Online_);
    }
    if (navCam2Online_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, navCam2Online_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof NavEventSensorOnlineStatus)) {
      return super.equals(obj);
    }
    NavEventSensorOnlineStatus other = (NavEventSensorOnlineStatus) obj;

    if (getSprayCam1Online()
        != other.getSprayCam1Online()) return false;
    if (getSprayCam2Online()
        != other.getSprayCam2Online()) return false;
    if (getSprayCam3Online()
        != other.getSprayCam3Online()) return false;
    if (getNavCam1Online()
        != other.getNavCam1Online()) return false;
    if (getNavCam2Online()
        != other.getNavCam2Online()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SPRAY_CAM1_ONLINE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSprayCam1Online());
    hash = (37 * hash) + SPRAY_CAM2_ONLINE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSprayCam2Online());
    hash = (37 * hash) + SPRAY_CAM3_ONLINE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSprayCam3Online());
    hash = (37 * hash) + NAV_CAM1_ONLINE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getNavCam1Online());
    hash = (37 * hash) + NAV_CAM2_ONLINE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getNavCam2Online());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static NavEventSensorOnlineStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NavEventSensorOnlineStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NavEventSensorOnlineStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NavEventSensorOnlineStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NavEventSensorOnlineStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NavEventSensorOnlineStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NavEventSensorOnlineStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static NavEventSensorOnlineStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static NavEventSensorOnlineStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static NavEventSensorOnlineStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static NavEventSensorOnlineStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static NavEventSensorOnlineStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(NavEventSensorOnlineStatus prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code qhx.proto.weve.event.odometry.NavEventSensorOnlineStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:qhx.proto.weve.event.odometry.NavEventSensorOnlineStatus)
          NavEventSensorOnlineStatusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EventNav.internal_static_qhx_proto_weve_event_odometry_NavEventSensorOnlineStatus_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EventNav.internal_static_qhx_proto_weve_event_odometry_NavEventSensorOnlineStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NavEventSensorOnlineStatus.class, Builder.class);
    }

    // Construct using com.qhx.proto.event.NavEventSensorOnlineStatus.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      sprayCam1Online_ = false;

      sprayCam2Online_ = false;

      sprayCam3Online_ = false;

      navCam1Online_ = false;

      navCam2Online_ = false;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return EventNav.internal_static_qhx_proto_weve_event_odometry_NavEventSensorOnlineStatus_descriptor;
    }

    @Override
    public NavEventSensorOnlineStatus getDefaultInstanceForType() {
      return NavEventSensorOnlineStatus.getDefaultInstance();
    }

    @Override
    public NavEventSensorOnlineStatus build() {
      NavEventSensorOnlineStatus result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public NavEventSensorOnlineStatus buildPartial() {
      NavEventSensorOnlineStatus result = new NavEventSensorOnlineStatus(this);
      result.sprayCam1Online_ = sprayCam1Online_;
      result.sprayCam2Online_ = sprayCam2Online_;
      result.sprayCam3Online_ = sprayCam3Online_;
      result.navCam1Online_ = navCam1Online_;
      result.navCam2Online_ = navCam2Online_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof NavEventSensorOnlineStatus) {
        return mergeFrom((NavEventSensorOnlineStatus)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(NavEventSensorOnlineStatus other) {
      if (other == NavEventSensorOnlineStatus.getDefaultInstance()) return this;
      if (other.getSprayCam1Online() != false) {
        setSprayCam1Online(other.getSprayCam1Online());
      }
      if (other.getSprayCam2Online() != false) {
        setSprayCam2Online(other.getSprayCam2Online());
      }
      if (other.getSprayCam3Online() != false) {
        setSprayCam3Online(other.getSprayCam3Online());
      }
      if (other.getNavCam1Online() != false) {
        setNavCam1Online(other.getNavCam1Online());
      }
      if (other.getNavCam2Online() != false) {
        setNavCam2Online(other.getNavCam2Online());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      NavEventSensorOnlineStatus parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (NavEventSensorOnlineStatus) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean sprayCam1Online_ ;
    /**
     * <code>bool spray_cam1_online = 1;</code>
     * @return The sprayCam1Online.
     */
    @Override
    public boolean getSprayCam1Online() {
      return sprayCam1Online_;
    }
    /**
     * <code>bool spray_cam1_online = 1;</code>
     * @param value The sprayCam1Online to set.
     * @return This builder for chaining.
     */
    public Builder setSprayCam1Online(boolean value) {
      
      sprayCam1Online_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool spray_cam1_online = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSprayCam1Online() {
      
      sprayCam1Online_ = false;
      onChanged();
      return this;
    }

    private boolean sprayCam2Online_ ;
    /**
     * <code>bool spray_cam2_online = 2;</code>
     * @return The sprayCam2Online.
     */
    @Override
    public boolean getSprayCam2Online() {
      return sprayCam2Online_;
    }
    /**
     * <code>bool spray_cam2_online = 2;</code>
     * @param value The sprayCam2Online to set.
     * @return This builder for chaining.
     */
    public Builder setSprayCam2Online(boolean value) {
      
      sprayCam2Online_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool spray_cam2_online = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSprayCam2Online() {
      
      sprayCam2Online_ = false;
      onChanged();
      return this;
    }

    private boolean sprayCam3Online_ ;
    /**
     * <code>bool spray_cam3_online = 3;</code>
     * @return The sprayCam3Online.
     */
    @Override
    public boolean getSprayCam3Online() {
      return sprayCam3Online_;
    }
    /**
     * <code>bool spray_cam3_online = 3;</code>
     * @param value The sprayCam3Online to set.
     * @return This builder for chaining.
     */
    public Builder setSprayCam3Online(boolean value) {
      
      sprayCam3Online_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool spray_cam3_online = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSprayCam3Online() {
      
      sprayCam3Online_ = false;
      onChanged();
      return this;
    }

    private boolean navCam1Online_ ;
    /**
     * <code>bool nav_cam1_online = 4;</code>
     * @return The navCam1Online.
     */
    @Override
    public boolean getNavCam1Online() {
      return navCam1Online_;
    }
    /**
     * <code>bool nav_cam1_online = 4;</code>
     * @param value The navCam1Online to set.
     * @return This builder for chaining.
     */
    public Builder setNavCam1Online(boolean value) {
      
      navCam1Online_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool nav_cam1_online = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearNavCam1Online() {
      
      navCam1Online_ = false;
      onChanged();
      return this;
    }

    private boolean navCam2Online_ ;
    /**
     * <code>bool nav_cam2_online = 5;</code>
     * @return The navCam2Online.
     */
    @Override
    public boolean getNavCam2Online() {
      return navCam2Online_;
    }
    /**
     * <code>bool nav_cam2_online = 5;</code>
     * @param value The navCam2Online to set.
     * @return This builder for chaining.
     */
    public Builder setNavCam2Online(boolean value) {
      
      navCam2Online_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool nav_cam2_online = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearNavCam2Online() {
      
      navCam2Online_ = false;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:qhx.proto.weve.event.odometry.NavEventSensorOnlineStatus)
  }

  // @@protoc_insertion_point(class_scope:qhx.proto.weve.event.odometry.NavEventSensorOnlineStatus)
  private static final NavEventSensorOnlineStatus DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new NavEventSensorOnlineStatus();
  }

  public static NavEventSensorOnlineStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NavEventSensorOnlineStatus>
      PARSER = new com.google.protobuf.AbstractParser<NavEventSensorOnlineStatus>() {
    @Override
    public NavEventSensorOnlineStatus parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NavEventSensorOnlineStatus(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NavEventSensorOnlineStatus> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<NavEventSensorOnlineStatus> getParserForType() {
    return PARSER;
  }

  @Override
  public NavEventSensorOnlineStatus getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

