// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pattern.proto

package com.qhx.proto.event;

public interface PatternOrBuilder extends
    // @@protoc_insertion_point(interface_extends:qhx.proto.weve.Pattern)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 索引
   * </pre>
   *
   * <code>uint32 index = 1;</code>
   * @return The index.
   */
  int getIndex();

  /**
   * <pre>
   * 工作模式
   * </pre>
   *
   * <code>.qhx.proto.weve.PatternType pattern_type = 2;</code>
   * @return The enum numeric value on the wire for patternType.
   */
  int getPatternTypeValue();
  /**
   * <pre>
   * 工作模式
   * </pre>
   *
   * <code>.qhx.proto.weve.PatternType pattern_type = 2;</code>
   * @return The patternType.
   */
  PatternType getPatternType();

  /**
   * <pre>
   * 工作模式参数
   * </pre>
   *
   * <code>bytes options = 3;</code>
   * @return The options.
   */
  com.google.protobuf.ByteString getOptions();
}
