// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pattern.proto

package com.qhx.proto.event;

public final class PatternOuterClass {
  private PatternOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_qhx_proto_weve_Pattern_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_qhx_proto_weve_Pattern_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_qhx_proto_weve_PatternWaypointsOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_qhx_proto_weve_PatternWaypointsOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_qhx_proto_weve_PatternCoveragePathOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_qhx_proto_weve_PatternCoveragePathOptions_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rpattern.proto\022\016qhx.proto.weve\032\tgeo.pro" +
      "to\"\\\n\007Pattern\022\r\n\005index\030\001 \001(\r\0221\n\014pattern_" +
      "type\030\002 \001(\0162\033.qhx.proto.weve.PatternType\022" +
      "\017\n\007options\030\003 \001(\014\"V\n\027PatternWaypointsOpti" +
      "ons\022\021\n\twaypoints\030\001 \003(\r\022(\n\ntrajectory\030\002 \003" +
      "(\0132\024.qhx.proto.weve.Pose\"\034\n\032PatternCover" +
      "agePathOptions*\304\001\n\013PatternType\022\030\n\024PATTER" +
      "N_TYPE_UNKNOWN\020\000\022\031\n\025PATTERN_TYPE_DEV_TES" +
      "T\020\001\022\032\n\026PATTERN_TYPE_WAYPOINTS\020\002\022\036\n\032PATTE" +
      "RN_TYPE_COVERAGE_PATH\020\003\022\036\n\032PATTERN_TYPE_" +
      "AIM_CROP_LINE\020\004\022$\n PATTERN_TYPE_FOLLOW_G" +
      "PS_BASELINE\020\005B\027\n\023com.qhx.proto.eventP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Geo.getDescriptor(),
        });
    internal_static_qhx_proto_weve_Pattern_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_qhx_proto_weve_Pattern_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_qhx_proto_weve_Pattern_descriptor,
        new String[] { "Index", "PatternType", "Options", });
    internal_static_qhx_proto_weve_PatternWaypointsOptions_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_qhx_proto_weve_PatternWaypointsOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_qhx_proto_weve_PatternWaypointsOptions_descriptor,
        new String[] { "Waypoints", "Trajectory", });
    internal_static_qhx_proto_weve_PatternCoveragePathOptions_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_qhx_proto_weve_PatternCoveragePathOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_qhx_proto_weve_PatternCoveragePathOptions_descriptor,
        new String[] { });
    Geo.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
