// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pattern.proto

package com.qhx.proto.event;

public interface PatternCoveragePathOptionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:qhx.proto.weve.PatternCoveragePathOptions)
    com.google.protobuf.MessageOrBuilder {
}
