// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: geo.proto

package com.qhx.proto.event;

public interface QuaternionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:qhx.proto.weve.Quaternion)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double x = 1;</code>
   * @return The x.
   */
  double getX();

  /**
   * <code>double y = 2;</code>
   * @return The y.
   */
  double getY();

  /**
   * <code>double z = 3;</code>
   * @return The z.
   */
  double getZ();

  /**
   * <code>double w = 4;</code>
   * @return The w.
   */
  double getW();
}
