// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spray_task.proto

package com.qhx.proto.event;

public interface SprayTaskSpraySwitchOrBuilder extends
    // @@protoc_insertion_point(interface_extends:qhx.proto.weve.task.spray.SprayTaskSpraySwitch)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 喷洒 开/关 - 是否进行识别，是否下发数据
   * </pre>
   *
   * <code>bool status = 1;</code>
   * @return The status.
   */
  boolean getStatus();
}
