// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spray_task.proto

package com.qhx.proto.event;

public interface SprayTaskPumpSwitchOrBuilder extends
    // @@protoc_insertion_point(interface_extends:qhx.proto.weve.task.spray.SprayTaskPumpSwitch)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 泵状态 开/关
   * </pre>
   *
   * <code>bool status = 1;</code>
   * @return The status.
   */
  boolean getStatus();
}
