// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spray_event.proto

package com.qhx.proto.event;

public interface SprayEventSprayTargetPositionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:qhx.proto.weve.event.spray.SprayEventSprayTargetPosition)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 帧数
   * </pre>
   *
   * <code>uint32 seq = 1;</code>
   * @return The seq.
   */
  int getSeq();

  /**
   * <pre>
   * 每一帧图像对应的所有喷洒目标点
   * </pre>
   *
   * <code>repeated .qhx.proto.weve.event.spray.SprayEventSprayTargetPoint position = 2;</code>
   */
  java.util.List<SprayEventSprayTargetPoint>
      getPositionList();
  /**
   * <pre>
   * 每一帧图像对应的所有喷洒目标点
   * </pre>
   *
   * <code>repeated .qhx.proto.weve.event.spray.SprayEventSprayTargetPoint position = 2;</code>
   */
  SprayEventSprayTargetPoint getPosition(int index);
  /**
   * <pre>
   * 每一帧图像对应的所有喷洒目标点
   * </pre>
   *
   * <code>repeated .qhx.proto.weve.event.spray.SprayEventSprayTargetPoint position = 2;</code>
   */
  int getPositionCount();
  /**
   * <pre>
   * 每一帧图像对应的所有喷洒目标点
   * </pre>
   *
   * <code>repeated .qhx.proto.weve.event.spray.SprayEventSprayTargetPoint position = 2;</code>
   */
  java.util.List<? extends SprayEventSprayTargetPointOrBuilder>
      getPositionOrBuilderList();
  /**
   * <pre>
   * 每一帧图像对应的所有喷洒目标点
   * </pre>
   *
   * <code>repeated .qhx.proto.weve.event.spray.SprayEventSprayTargetPoint position = 2;</code>
   */
  SprayEventSprayTargetPointOrBuilder getPositionOrBuilder(
      int index);
}
