// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: spray_event.proto

package com.qhx.proto.event;

public interface SprayEventSprayTargetPointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:qhx.proto.weve.event.spray.SprayEventSprayTargetPoint)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 目标点像素坐标
   * </pre>
   *
   * <code>.qhx.proto.weve.event.spray.SprayEventSprayPixel pixel = 1;</code>
   * @return Whether the pixel field is set.
   */
  boolean hasPixel();
  /**
   * <pre>
   * 目标点像素坐标
   * </pre>
   *
   * <code>.qhx.proto.weve.event.spray.SprayEventSprayPixel pixel = 1;</code>
   * @return The pixel.
   */
  SprayEventSprayPixel getPixel();
  /**
   * <pre>
   * 目标点像素坐标
   * </pre>
   *
   * <code>.qhx.proto.weve.event.spray.SprayEventSprayPixel pixel = 1;</code>
   */
  SprayEventSprayPixelOrBuilder getPixelOrBuilder();

  /**
   * <pre>
   * 目标点世界坐标
   * </pre>
   *
   * <code>.qhx.proto.weve.Point point = 2;</code>
   * @return Whether the point field is set.
   */
  boolean hasPoint();
  /**
   * <pre>
   * 目标点世界坐标
   * </pre>
   *
   * <code>.qhx.proto.weve.Point point = 2;</code>
   * @return The point.
   */
  Point getPoint();
  /**
   * <pre>
   * 目标点世界坐标
   * </pre>
   *
   * <code>.qhx.proto.weve.Point point = 2;</code>
   */
  PointOrBuilder getPointOrBuilder();
}
