// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trigger.proto

package com.qhx.proto.event;

/**
 * <pre>
 * 触发器类型
 * </pre>
 *
 * Protobuf enum {@code qhx.proto.weve.TriggerType}
 */
public enum TriggerType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>TRIGGER_TYPE_UNKNOWN = 0;</code>
   */
  TRIGGER_TYPE_UNKNOWN(0),
  /**
   * <pre>
   * 任务触发器
   * </pre>
   *
   * <code>TRIGGER_TYPE_TASK = 1;</code>
   */
  TRIGGER_TYPE_TASK(1),
  /**
   * <pre>
   * 路径点触发器
   * </pre>
   *
   * <code>TRIGGER_TYPE_WAYPOINT = 2;</code>
   */
  TRIGGER_TYPE_WAYPOINT(2),
  /**
   * <pre>
   * 时间触发器
   * </pre>
   *
   * <code>TRIGGER_TYPE_TIME = 3;</code>
   */
  TRIGGER_TYPE_TIME(3),
  /**
   * <pre>
   * 围栏触发器
   * </pre>
   *
   * <code>TRIGGER_FENCE_VIOLATION = 4;</code>
   */
  TRIGGER_FENCE_VIOLATION(4),
  /**
   * <pre>
   * 地理信息触发器
   * </pre>
   *
   * <code>TRIGGER_TYPE_GIS = 5;</code>
   */
  TRIGGER_TYPE_GIS(5),
  /**
   * <pre>
   * 外部任务调用触发器
   * </pre>
   *
   * <code>TRIGGER_TYPE_TASKCALL = 6;</code>
   */
  TRIGGER_TYPE_TASKCALL(6),
  /**
   * <pre>
   * 脚本触发器
   * </pre>
   *
   * <code>TRIGGER_TYPE_SCRIPT = 64;</code>
   */
  TRIGGER_TYPE_SCRIPT(64),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>TRIGGER_TYPE_UNKNOWN = 0;</code>
   */
  public static final int TRIGGER_TYPE_UNKNOWN_VALUE = 0;
  /**
   * <pre>
   * 任务触发器
   * </pre>
   *
   * <code>TRIGGER_TYPE_TASK = 1;</code>
   */
  public static final int TRIGGER_TYPE_TASK_VALUE = 1;
  /**
   * <pre>
   * 路径点触发器
   * </pre>
   *
   * <code>TRIGGER_TYPE_WAYPOINT = 2;</code>
   */
  public static final int TRIGGER_TYPE_WAYPOINT_VALUE = 2;
  /**
   * <pre>
   * 时间触发器
   * </pre>
   *
   * <code>TRIGGER_TYPE_TIME = 3;</code>
   */
  public static final int TRIGGER_TYPE_TIME_VALUE = 3;
  /**
   * <pre>
   * 围栏触发器
   * </pre>
   *
   * <code>TRIGGER_FENCE_VIOLATION = 4;</code>
   */
  public static final int TRIGGER_FENCE_VIOLATION_VALUE = 4;
  /**
   * <pre>
   * 地理信息触发器
   * </pre>
   *
   * <code>TRIGGER_TYPE_GIS = 5;</code>
   */
  public static final int TRIGGER_TYPE_GIS_VALUE = 5;
  /**
   * <pre>
   * 外部任务调用触发器
   * </pre>
   *
   * <code>TRIGGER_TYPE_TASKCALL = 6;</code>
   */
  public static final int TRIGGER_TYPE_TASKCALL_VALUE = 6;
  /**
   * <pre>
   * 脚本触发器
   * </pre>
   *
   * <code>TRIGGER_TYPE_SCRIPT = 64;</code>
   */
  public static final int TRIGGER_TYPE_SCRIPT_VALUE = 64;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static TriggerType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static TriggerType forNumber(int value) {
    switch (value) {
      case 0: return TRIGGER_TYPE_UNKNOWN;
      case 1: return TRIGGER_TYPE_TASK;
      case 2: return TRIGGER_TYPE_WAYPOINT;
      case 3: return TRIGGER_TYPE_TIME;
      case 4: return TRIGGER_FENCE_VIOLATION;
      case 5: return TRIGGER_TYPE_GIS;
      case 6: return TRIGGER_TYPE_TASKCALL;
      case 64: return TRIGGER_TYPE_SCRIPT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TriggerType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TriggerType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TriggerType>() {
          public TriggerType findValueByNumber(int number) {
            return TriggerType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return TriggerOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final TriggerType[] VALUES = values();

  public static TriggerType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TriggerType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:qhx.proto.weve.TriggerType)
}

