// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pos.proto

package com.qhx.proto;

public interface OrderNotifyRequestProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OrderNotifyRequestProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>fixed64 order_id = 1;</code>
   * @return The orderId.
   */
  long getOrderId();

  /**
   * <code>string status = 2;</code>
   * @return The status.
   */
  String getStatus();
  /**
   * <code>string status = 2;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
