// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pay.proto

package com.qhx.proto;

/**
 * Protobuf type {@code WxPayInvokeProto}
 */
public final class WxPayInvokeProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WxPayInvokeProto)
    WxPayInvokeProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WxPayInvokeProto.newBuilder() to construct.
  private WxPayInvokeProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WxPayInvokeProto() {
    timeStamp_ = "";
    nonceStr_ = "";
    packageStr_ = "";
    signType_ = "";
    paySign_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new WxPayInvokeProto();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WxPayInvokeProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            timeStamp_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            nonceStr_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            packageStr_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            signType_ = s;
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            paySign_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.qhx.proto.PayProto.internal_static_WxPayInvokeProto_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.qhx.proto.PayProto.internal_static_WxPayInvokeProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            WxPayInvokeProto.class, Builder.class);
  }

  public static final int TIME_STAMP_FIELD_NUMBER = 1;
  private volatile Object timeStamp_;
  /**
   * <code>string time_stamp = 1;</code>
   * @return The timeStamp.
   */
  @Override
  public String getTimeStamp() {
    Object ref = timeStamp_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      timeStamp_ = s;
      return s;
    }
  }
  /**
   * <code>string time_stamp = 1;</code>
   * @return The bytes for timeStamp.
   */
  @Override
  public com.google.protobuf.ByteString
      getTimeStampBytes() {
    Object ref = timeStamp_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      timeStamp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NONCE_STR_FIELD_NUMBER = 2;
  private volatile Object nonceStr_;
  /**
   * <code>string nonce_str = 2;</code>
   * @return The nonceStr.
   */
  @Override
  public String getNonceStr() {
    Object ref = nonceStr_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      nonceStr_ = s;
      return s;
    }
  }
  /**
   * <code>string nonce_str = 2;</code>
   * @return The bytes for nonceStr.
   */
  @Override
  public com.google.protobuf.ByteString
      getNonceStrBytes() {
    Object ref = nonceStr_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      nonceStr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PACKAGE_STR_FIELD_NUMBER = 3;
  private volatile Object packageStr_;
  /**
   * <code>string package_str = 3;</code>
   * @return The packageStr.
   */
  @Override
  public String getPackageStr() {
    Object ref = packageStr_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      packageStr_ = s;
      return s;
    }
  }
  /**
   * <code>string package_str = 3;</code>
   * @return The bytes for packageStr.
   */
  @Override
  public com.google.protobuf.ByteString
      getPackageStrBytes() {
    Object ref = packageStr_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      packageStr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SIGN_TYPE_FIELD_NUMBER = 4;
  private volatile Object signType_;
  /**
   * <code>string sign_type = 4;</code>
   * @return The signType.
   */
  @Override
  public String getSignType() {
    Object ref = signType_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      signType_ = s;
      return s;
    }
  }
  /**
   * <code>string sign_type = 4;</code>
   * @return The bytes for signType.
   */
  @Override
  public com.google.protobuf.ByteString
      getSignTypeBytes() {
    Object ref = signType_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      signType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAY_SIGN_FIELD_NUMBER = 5;
  private volatile Object paySign_;
  /**
   * <code>string pay_sign = 5;</code>
   * @return The paySign.
   */
  @Override
  public String getPaySign() {
    Object ref = paySign_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      paySign_ = s;
      return s;
    }
  }
  /**
   * <code>string pay_sign = 5;</code>
   * @return The bytes for paySign.
   */
  @Override
  public com.google.protobuf.ByteString
      getPaySignBytes() {
    Object ref = paySign_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      paySign_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTimeStampBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, timeStamp_);
    }
    if (!getNonceStrBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nonceStr_);
    }
    if (!getPackageStrBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, packageStr_);
    }
    if (!getSignTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, signType_);
    }
    if (!getPaySignBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, paySign_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTimeStampBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, timeStamp_);
    }
    if (!getNonceStrBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nonceStr_);
    }
    if (!getPackageStrBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, packageStr_);
    }
    if (!getSignTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, signType_);
    }
    if (!getPaySignBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, paySign_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof WxPayInvokeProto)) {
      return super.equals(obj);
    }
    WxPayInvokeProto other = (WxPayInvokeProto) obj;

    if (!getTimeStamp()
        .equals(other.getTimeStamp())) return false;
    if (!getNonceStr()
        .equals(other.getNonceStr())) return false;
    if (!getPackageStr()
        .equals(other.getPackageStr())) return false;
    if (!getSignType()
        .equals(other.getSignType())) return false;
    if (!getPaySign()
        .equals(other.getPaySign())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIME_STAMP_FIELD_NUMBER;
    hash = (53 * hash) + getTimeStamp().hashCode();
    hash = (37 * hash) + NONCE_STR_FIELD_NUMBER;
    hash = (53 * hash) + getNonceStr().hashCode();
    hash = (37 * hash) + PACKAGE_STR_FIELD_NUMBER;
    hash = (53 * hash) + getPackageStr().hashCode();
    hash = (37 * hash) + SIGN_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getSignType().hashCode();
    hash = (37 * hash) + PAY_SIGN_FIELD_NUMBER;
    hash = (53 * hash) + getPaySign().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static WxPayInvokeProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static WxPayInvokeProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static WxPayInvokeProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static WxPayInvokeProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static WxPayInvokeProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static WxPayInvokeProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static WxPayInvokeProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static WxPayInvokeProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static WxPayInvokeProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static WxPayInvokeProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static WxPayInvokeProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static WxPayInvokeProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(WxPayInvokeProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code WxPayInvokeProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WxPayInvokeProto)
      WxPayInvokeProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qhx.proto.PayProto.internal_static_WxPayInvokeProto_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qhx.proto.PayProto.internal_static_WxPayInvokeProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              WxPayInvokeProto.class, Builder.class);
    }

    // Construct using com.qhx.proto.WxPayInvokeProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      timeStamp_ = "";

      nonceStr_ = "";

      packageStr_ = "";

      signType_ = "";

      paySign_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.qhx.proto.PayProto.internal_static_WxPayInvokeProto_descriptor;
    }

    @Override
    public WxPayInvokeProto getDefaultInstanceForType() {
      return WxPayInvokeProto.getDefaultInstance();
    }

    @Override
    public WxPayInvokeProto build() {
      WxPayInvokeProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public WxPayInvokeProto buildPartial() {
      WxPayInvokeProto result = new WxPayInvokeProto(this);
      result.timeStamp_ = timeStamp_;
      result.nonceStr_ = nonceStr_;
      result.packageStr_ = packageStr_;
      result.signType_ = signType_;
      result.paySign_ = paySign_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof WxPayInvokeProto) {
        return mergeFrom((WxPayInvokeProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(WxPayInvokeProto other) {
      if (other == WxPayInvokeProto.getDefaultInstance()) return this;
      if (!other.getTimeStamp().isEmpty()) {
        timeStamp_ = other.timeStamp_;
        onChanged();
      }
      if (!other.getNonceStr().isEmpty()) {
        nonceStr_ = other.nonceStr_;
        onChanged();
      }
      if (!other.getPackageStr().isEmpty()) {
        packageStr_ = other.packageStr_;
        onChanged();
      }
      if (!other.getSignType().isEmpty()) {
        signType_ = other.signType_;
        onChanged();
      }
      if (!other.getPaySign().isEmpty()) {
        paySign_ = other.paySign_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      WxPayInvokeProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (WxPayInvokeProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object timeStamp_ = "";
    /**
     * <code>string time_stamp = 1;</code>
     * @return The timeStamp.
     */
    public String getTimeStamp() {
      Object ref = timeStamp_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        timeStamp_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string time_stamp = 1;</code>
     * @return The bytes for timeStamp.
     */
    public com.google.protobuf.ByteString
        getTimeStampBytes() {
      Object ref = timeStamp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        timeStamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string time_stamp = 1;</code>
     * @param value The timeStamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimeStamp(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      timeStamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string time_stamp = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeStamp() {
      
      timeStamp_ = getDefaultInstance().getTimeStamp();
      onChanged();
      return this;
    }
    /**
     * <code>string time_stamp = 1;</code>
     * @param value The bytes for timeStamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimeStampBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      timeStamp_ = value;
      onChanged();
      return this;
    }

    private Object nonceStr_ = "";
    /**
     * <code>string nonce_str = 2;</code>
     * @return The nonceStr.
     */
    public String getNonceStr() {
      Object ref = nonceStr_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        nonceStr_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string nonce_str = 2;</code>
     * @return The bytes for nonceStr.
     */
    public com.google.protobuf.ByteString
        getNonceStrBytes() {
      Object ref = nonceStr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        nonceStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string nonce_str = 2;</code>
     * @param value The nonceStr to set.
     * @return This builder for chaining.
     */
    public Builder setNonceStr(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nonceStr_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string nonce_str = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNonceStr() {
      
      nonceStr_ = getDefaultInstance().getNonceStr();
      onChanged();
      return this;
    }
    /**
     * <code>string nonce_str = 2;</code>
     * @param value The bytes for nonceStr to set.
     * @return This builder for chaining.
     */
    public Builder setNonceStrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nonceStr_ = value;
      onChanged();
      return this;
    }

    private Object packageStr_ = "";
    /**
     * <code>string package_str = 3;</code>
     * @return The packageStr.
     */
    public String getPackageStr() {
      Object ref = packageStr_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        packageStr_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string package_str = 3;</code>
     * @return The bytes for packageStr.
     */
    public com.google.protobuf.ByteString
        getPackageStrBytes() {
      Object ref = packageStr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        packageStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string package_str = 3;</code>
     * @param value The packageStr to set.
     * @return This builder for chaining.
     */
    public Builder setPackageStr(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      packageStr_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string package_str = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPackageStr() {
      
      packageStr_ = getDefaultInstance().getPackageStr();
      onChanged();
      return this;
    }
    /**
     * <code>string package_str = 3;</code>
     * @param value The bytes for packageStr to set.
     * @return This builder for chaining.
     */
    public Builder setPackageStrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      packageStr_ = value;
      onChanged();
      return this;
    }

    private Object signType_ = "";
    /**
     * <code>string sign_type = 4;</code>
     * @return The signType.
     */
    public String getSignType() {
      Object ref = signType_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        signType_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string sign_type = 4;</code>
     * @return The bytes for signType.
     */
    public com.google.protobuf.ByteString
        getSignTypeBytes() {
      Object ref = signType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        signType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sign_type = 4;</code>
     * @param value The signType to set.
     * @return This builder for chaining.
     */
    public Builder setSignType(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      signType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sign_type = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSignType() {
      
      signType_ = getDefaultInstance().getSignType();
      onChanged();
      return this;
    }
    /**
     * <code>string sign_type = 4;</code>
     * @param value The bytes for signType to set.
     * @return This builder for chaining.
     */
    public Builder setSignTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      signType_ = value;
      onChanged();
      return this;
    }

    private Object paySign_ = "";
    /**
     * <code>string pay_sign = 5;</code>
     * @return The paySign.
     */
    public String getPaySign() {
      Object ref = paySign_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        paySign_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string pay_sign = 5;</code>
     * @return The bytes for paySign.
     */
    public com.google.protobuf.ByteString
        getPaySignBytes() {
      Object ref = paySign_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        paySign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pay_sign = 5;</code>
     * @param value The paySign to set.
     * @return This builder for chaining.
     */
    public Builder setPaySign(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      paySign_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string pay_sign = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPaySign() {
      
      paySign_ = getDefaultInstance().getPaySign();
      onChanged();
      return this;
    }
    /**
     * <code>string pay_sign = 5;</code>
     * @param value The bytes for paySign to set.
     * @return This builder for chaining.
     */
    public Builder setPaySignBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      paySign_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WxPayInvokeProto)
  }

  // @@protoc_insertion_point(class_scope:WxPayInvokeProto)
  private static final WxPayInvokeProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new WxPayInvokeProto();
  }

  public static WxPayInvokeProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WxPayInvokeProto>
      PARSER = new com.google.protobuf.AbstractParser<WxPayInvokeProto>() {
    @Override
    public WxPayInvokeProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WxPayInvokeProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WxPayInvokeProto> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<WxPayInvokeProto> getParserForType() {
    return PARSER;
  }

  @Override
  public WxPayInvokeProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

