// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: command.proto

package qhx.proto.weve.update;

public final class CommandOuterClass {
  private CommandOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * 命令类型
   * </pre>
   *
   * Protobuf enum {@code qhx.proto.weve.update.CommandType}
   */
  public enum CommandType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 未知命令
     * </pre>
     *
     * <code>COMMAND_TYPE_UNKNOWN = 0;</code>
     */
    COMMAND_TYPE_UNKNOWN(0),
    /**
     * <pre>
     * 更新命令
     * </pre>
     *
     * <code>COMMAND_TYPE_UPDATE_REQUEST = 1;</code>
     */
    COMMAND_TYPE_UPDATE_REQUEST(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 未知命令
     * </pre>
     *
     * <code>COMMAND_TYPE_UNKNOWN = 0;</code>
     */
    public static final int COMMAND_TYPE_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * 更新命令
     * </pre>
     *
     * <code>COMMAND_TYPE_UPDATE_REQUEST = 1;</code>
     */
    public static final int COMMAND_TYPE_UPDATE_REQUEST_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CommandType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static CommandType forNumber(int value) {
      switch (value) {
        case 0: return COMMAND_TYPE_UNKNOWN;
        case 1: return COMMAND_TYPE_UPDATE_REQUEST;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CommandType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CommandType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CommandType>() {
            public CommandType findValueByNumber(int number) {
              return CommandType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return qhx.proto.weve.update.CommandOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final CommandType[] VALUES = values();

    public static CommandType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CommandType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:qhx.proto.weve.update.CommandType)
  }

  public interface CommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:qhx.proto.weve.update.Command)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 命令类型
     * </pre>
     *
     * <code>.qhx.proto.weve.update.CommandType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <pre>
     * 命令类型
     * </pre>
     *
     * <code>.qhx.proto.weve.update.CommandType type = 1;</code>
     * @return The type.
     */
    qhx.proto.weve.update.CommandOuterClass.CommandType getType();

    /**
     * <pre>
     * 命令参数
     * </pre>
     *
     * <code>bytes options = 2;</code>
     * @return The options.
     */
    com.google.protobuf.ByteString getOptions();

    /**
     * <pre>
     * 清单（包与包中文件元数据）
     * </pre>
     *
     * <code>.qhx.proto.weve.update.PackageManifest manifest = 3;</code>
     * @return Whether the manifest field is set.
     */
    boolean hasManifest();
    /**
     * <pre>
     * 清单（包与包中文件元数据）
     * </pre>
     *
     * <code>.qhx.proto.weve.update.PackageManifest manifest = 3;</code>
     * @return The manifest.
     */
    qhx.proto.weve.update.Manifest.PackageManifest getManifest();
    /**
     * <pre>
     * 清单（包与包中文件元数据）
     * </pre>
     *
     * <code>.qhx.proto.weve.update.PackageManifest manifest = 3;</code>
     */
    qhx.proto.weve.update.Manifest.PackageManifestOrBuilder getManifestOrBuilder();

    /**
     * <pre>
     * 包：URI 方式
     * </pre>
     *
     * <code>string package_uri = 4;</code>
     * @return Whether the packageUri field is set.
     */
    boolean hasPackageUri();
    /**
     * <pre>
     * 包：URI 方式
     * </pre>
     *
     * <code>string package_uri = 4;</code>
     * @return The packageUri.
     */
    java.lang.String getPackageUri();
    /**
     * <pre>
     * 包：URI 方式
     * </pre>
     *
     * <code>string package_uri = 4;</code>
     * @return The bytes for packageUri.
     */
    com.google.protobuf.ByteString
        getPackageUriBytes();

    /**
     * <pre>
     * 包：命令直接携带方式
     * </pre>
     *
     * <code>bytes package_raw = 5;</code>
     * @return Whether the packageRaw field is set.
     */
    boolean hasPackageRaw();
    /**
     * <pre>
     * 包：命令直接携带方式
     * </pre>
     *
     * <code>bytes package_raw = 5;</code>
     * @return The packageRaw.
     */
    com.google.protobuf.ByteString getPackageRaw();

    public qhx.proto.weve.update.CommandOuterClass.Command.PackageCase getPackageCase();
  }
  /**
   * <pre>
   * 命令
   * </pre>
   *
   * Protobuf type {@code qhx.proto.weve.update.Command}
   */
  public static final class Command extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:qhx.proto.weve.update.Command)
      CommandOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Command.newBuilder() to construct.
    private Command(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Command() {
      type_ = 0;
      options_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Command();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Command(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {

              options_ = input.readBytes();
              break;
            }
            case 26: {
              qhx.proto.weve.update.Manifest.PackageManifest.Builder subBuilder = null;
              if (manifest_ != null) {
                subBuilder = manifest_.toBuilder();
              }
              manifest_ = input.readMessage(qhx.proto.weve.update.Manifest.PackageManifest.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(manifest_);
                manifest_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              packageCase_ = 4;
              package_ = s;
              break;
            }
            case 42: {
              packageCase_ = 5;
              package_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return qhx.proto.weve.update.CommandOuterClass.internal_static_qhx_proto_weve_update_Command_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return qhx.proto.weve.update.CommandOuterClass.internal_static_qhx_proto_weve_update_Command_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              qhx.proto.weve.update.CommandOuterClass.Command.class, qhx.proto.weve.update.CommandOuterClass.Command.Builder.class);
    }

    private int packageCase_ = 0;
    private java.lang.Object package_;
    public enum PackageCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      PACKAGE_URI(4),
      PACKAGE_RAW(5),
      PACKAGE_NOT_SET(0);
      private final int value;
      private PackageCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PackageCase valueOf(int value) {
        return forNumber(value);
      }

      public static PackageCase forNumber(int value) {
        switch (value) {
          case 4: return PACKAGE_URI;
          case 5: return PACKAGE_RAW;
          case 0: return PACKAGE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public PackageCase
    getPackageCase() {
      return PackageCase.forNumber(
          packageCase_);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <pre>
     * 命令类型
     * </pre>
     *
     * <code>.qhx.proto.weve.update.CommandType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * 命令类型
     * </pre>
     *
     * <code>.qhx.proto.weve.update.CommandType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override public qhx.proto.weve.update.CommandOuterClass.CommandType getType() {
      @SuppressWarnings("deprecation")
      qhx.proto.weve.update.CommandOuterClass.CommandType result = qhx.proto.weve.update.CommandOuterClass.CommandType.valueOf(type_);
      return result == null ? qhx.proto.weve.update.CommandOuterClass.CommandType.UNRECOGNIZED : result;
    }

    public static final int OPTIONS_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString options_;
    /**
     * <pre>
     * 命令参数
     * </pre>
     *
     * <code>bytes options = 2;</code>
     * @return The options.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getOptions() {
      return options_;
    }

    public static final int MANIFEST_FIELD_NUMBER = 3;
    private qhx.proto.weve.update.Manifest.PackageManifest manifest_;
    /**
     * <pre>
     * 清单（包与包中文件元数据）
     * </pre>
     *
     * <code>.qhx.proto.weve.update.PackageManifest manifest = 3;</code>
     * @return Whether the manifest field is set.
     */
    @java.lang.Override
    public boolean hasManifest() {
      return manifest_ != null;
    }
    /**
     * <pre>
     * 清单（包与包中文件元数据）
     * </pre>
     *
     * <code>.qhx.proto.weve.update.PackageManifest manifest = 3;</code>
     * @return The manifest.
     */
    @java.lang.Override
    public qhx.proto.weve.update.Manifest.PackageManifest getManifest() {
      return manifest_ == null ? qhx.proto.weve.update.Manifest.PackageManifest.getDefaultInstance() : manifest_;
    }
    /**
     * <pre>
     * 清单（包与包中文件元数据）
     * </pre>
     *
     * <code>.qhx.proto.weve.update.PackageManifest manifest = 3;</code>
     */
    @java.lang.Override
    public qhx.proto.weve.update.Manifest.PackageManifestOrBuilder getManifestOrBuilder() {
      return getManifest();
    }

    public static final int PACKAGE_URI_FIELD_NUMBER = 4;
    /**
     * <pre>
     * 包：URI 方式
     * </pre>
     *
     * <code>string package_uri = 4;</code>
     * @return Whether the packageUri field is set.
     */
    public boolean hasPackageUri() {
      return packageCase_ == 4;
    }
    /**
     * <pre>
     * 包：URI 方式
     * </pre>
     *
     * <code>string package_uri = 4;</code>
     * @return The packageUri.
     */
    public java.lang.String getPackageUri() {
      java.lang.Object ref = "";
      if (packageCase_ == 4) {
        ref = package_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (packageCase_ == 4) {
          package_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 包：URI 方式
     * </pre>
     *
     * <code>string package_uri = 4;</code>
     * @return The bytes for packageUri.
     */
    public com.google.protobuf.ByteString
        getPackageUriBytes() {
      java.lang.Object ref = "";
      if (packageCase_ == 4) {
        ref = package_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (packageCase_ == 4) {
          package_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PACKAGE_RAW_FIELD_NUMBER = 5;
    /**
     * <pre>
     * 包：命令直接携带方式
     * </pre>
     *
     * <code>bytes package_raw = 5;</code>
     * @return Whether the packageRaw field is set.
     */
    @java.lang.Override
    public boolean hasPackageRaw() {
      return packageCase_ == 5;
    }
    /**
     * <pre>
     * 包：命令直接携带方式
     * </pre>
     *
     * <code>bytes package_raw = 5;</code>
     * @return The packageRaw.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPackageRaw() {
      if (packageCase_ == 5) {
        return (com.google.protobuf.ByteString) package_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != qhx.proto.weve.update.CommandOuterClass.CommandType.COMMAND_TYPE_UNKNOWN.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (!options_.isEmpty()) {
        output.writeBytes(2, options_);
      }
      if (manifest_ != null) {
        output.writeMessage(3, getManifest());
      }
      if (packageCase_ == 4) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, package_);
      }
      if (packageCase_ == 5) {
        output.writeBytes(
            5, (com.google.protobuf.ByteString) package_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != qhx.proto.weve.update.CommandOuterClass.CommandType.COMMAND_TYPE_UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (!options_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, options_);
      }
      if (manifest_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getManifest());
      }
      if (packageCase_ == 4) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, package_);
      }
      if (packageCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(
              5, (com.google.protobuf.ByteString) package_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof qhx.proto.weve.update.CommandOuterClass.Command)) {
        return super.equals(obj);
      }
      qhx.proto.weve.update.CommandOuterClass.Command other = (qhx.proto.weve.update.CommandOuterClass.Command) obj;

      if (type_ != other.type_) return false;
      if (!getOptions()
          .equals(other.getOptions())) return false;
      if (hasManifest() != other.hasManifest()) return false;
      if (hasManifest()) {
        if (!getManifest()
            .equals(other.getManifest())) return false;
      }
      if (!getPackageCase().equals(other.getPackageCase())) return false;
      switch (packageCase_) {
        case 4:
          if (!getPackageUri()
              .equals(other.getPackageUri())) return false;
          break;
        case 5:
          if (!getPackageRaw()
              .equals(other.getPackageRaw())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + OPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getOptions().hashCode();
      if (hasManifest()) {
        hash = (37 * hash) + MANIFEST_FIELD_NUMBER;
        hash = (53 * hash) + getManifest().hashCode();
      }
      switch (packageCase_) {
        case 4:
          hash = (37 * hash) + PACKAGE_URI_FIELD_NUMBER;
          hash = (53 * hash) + getPackageUri().hashCode();
          break;
        case 5:
          hash = (37 * hash) + PACKAGE_RAW_FIELD_NUMBER;
          hash = (53 * hash) + getPackageRaw().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static qhx.proto.weve.update.CommandOuterClass.Command parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qhx.proto.weve.update.CommandOuterClass.Command parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qhx.proto.weve.update.CommandOuterClass.Command parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qhx.proto.weve.update.CommandOuterClass.Command parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qhx.proto.weve.update.CommandOuterClass.Command parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static qhx.proto.weve.update.CommandOuterClass.Command parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static qhx.proto.weve.update.CommandOuterClass.Command parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static qhx.proto.weve.update.CommandOuterClass.Command parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static qhx.proto.weve.update.CommandOuterClass.Command parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static qhx.proto.weve.update.CommandOuterClass.Command parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static qhx.proto.weve.update.CommandOuterClass.Command parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static qhx.proto.weve.update.CommandOuterClass.Command parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(qhx.proto.weve.update.CommandOuterClass.Command prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 命令
     * </pre>
     *
     * Protobuf type {@code qhx.proto.weve.update.Command}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:qhx.proto.weve.update.Command)
        qhx.proto.weve.update.CommandOuterClass.CommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return qhx.proto.weve.update.CommandOuterClass.internal_static_qhx_proto_weve_update_Command_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return qhx.proto.weve.update.CommandOuterClass.internal_static_qhx_proto_weve_update_Command_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                qhx.proto.weve.update.CommandOuterClass.Command.class, qhx.proto.weve.update.CommandOuterClass.Command.Builder.class);
      }

      // Construct using qhx.proto.weve.update.CommandOuterClass.Command.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        options_ = com.google.protobuf.ByteString.EMPTY;

        if (manifestBuilder_ == null) {
          manifest_ = null;
        } else {
          manifest_ = null;
          manifestBuilder_ = null;
        }
        packageCase_ = 0;
        package_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return qhx.proto.weve.update.CommandOuterClass.internal_static_qhx_proto_weve_update_Command_descriptor;
      }

      @java.lang.Override
      public qhx.proto.weve.update.CommandOuterClass.Command getDefaultInstanceForType() {
        return qhx.proto.weve.update.CommandOuterClass.Command.getDefaultInstance();
      }

      @java.lang.Override
      public qhx.proto.weve.update.CommandOuterClass.Command build() {
        qhx.proto.weve.update.CommandOuterClass.Command result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public qhx.proto.weve.update.CommandOuterClass.Command buildPartial() {
        qhx.proto.weve.update.CommandOuterClass.Command result = new qhx.proto.weve.update.CommandOuterClass.Command(this);
        result.type_ = type_;
        result.options_ = options_;
        if (manifestBuilder_ == null) {
          result.manifest_ = manifest_;
        } else {
          result.manifest_ = manifestBuilder_.build();
        }
        if (packageCase_ == 4) {
          result.package_ = package_;
        }
        if (packageCase_ == 5) {
          result.package_ = package_;
        }
        result.packageCase_ = packageCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof qhx.proto.weve.update.CommandOuterClass.Command) {
          return mergeFrom((qhx.proto.weve.update.CommandOuterClass.Command)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(qhx.proto.weve.update.CommandOuterClass.Command other) {
        if (other == qhx.proto.weve.update.CommandOuterClass.Command.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getOptions() != com.google.protobuf.ByteString.EMPTY) {
          setOptions(other.getOptions());
        }
        if (other.hasManifest()) {
          mergeManifest(other.getManifest());
        }
        switch (other.getPackageCase()) {
          case PACKAGE_URI: {
            packageCase_ = 4;
            package_ = other.package_;
            onChanged();
            break;
          }
          case PACKAGE_RAW: {
            setPackageRaw(other.getPackageRaw());
            break;
          }
          case PACKAGE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        qhx.proto.weve.update.CommandOuterClass.Command parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (qhx.proto.weve.update.CommandOuterClass.Command) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int packageCase_ = 0;
      private java.lang.Object package_;
      public PackageCase
          getPackageCase() {
        return PackageCase.forNumber(
            packageCase_);
      }

      public Builder clearPackage() {
        packageCase_ = 0;
        package_ = null;
        onChanged();
        return this;
      }


      private int type_ = 0;
      /**
       * <pre>
       * 命令类型
       * </pre>
       *
       * <code>.qhx.proto.weve.update.CommandType type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       * 命令类型
       * </pre>
       *
       * <code>.qhx.proto.weve.update.CommandType type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 命令类型
       * </pre>
       *
       * <code>.qhx.proto.weve.update.CommandType type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public qhx.proto.weve.update.CommandOuterClass.CommandType getType() {
        @SuppressWarnings("deprecation")
        qhx.proto.weve.update.CommandOuterClass.CommandType result = qhx.proto.weve.update.CommandOuterClass.CommandType.valueOf(type_);
        return result == null ? qhx.proto.weve.update.CommandOuterClass.CommandType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 命令类型
       * </pre>
       *
       * <code>.qhx.proto.weve.update.CommandType type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(qhx.proto.weve.update.CommandOuterClass.CommandType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 命令类型
       * </pre>
       *
       * <code>.qhx.proto.weve.update.CommandType type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString options_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 命令参数
       * </pre>
       *
       * <code>bytes options = 2;</code>
       * @return The options.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getOptions() {
        return options_;
      }
      /**
       * <pre>
       * 命令参数
       * </pre>
       *
       * <code>bytes options = 2;</code>
       * @param value The options to set.
       * @return This builder for chaining.
       */
      public Builder setOptions(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        options_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 命令参数
       * </pre>
       *
       * <code>bytes options = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOptions() {
        
        options_ = getDefaultInstance().getOptions();
        onChanged();
        return this;
      }

      private qhx.proto.weve.update.Manifest.PackageManifest manifest_;
      private com.google.protobuf.SingleFieldBuilderV3<
          qhx.proto.weve.update.Manifest.PackageManifest, qhx.proto.weve.update.Manifest.PackageManifest.Builder, qhx.proto.weve.update.Manifest.PackageManifestOrBuilder> manifestBuilder_;
      /**
       * <pre>
       * 清单（包与包中文件元数据）
       * </pre>
       *
       * <code>.qhx.proto.weve.update.PackageManifest manifest = 3;</code>
       * @return Whether the manifest field is set.
       */
      public boolean hasManifest() {
        return manifestBuilder_ != null || manifest_ != null;
      }
      /**
       * <pre>
       * 清单（包与包中文件元数据）
       * </pre>
       *
       * <code>.qhx.proto.weve.update.PackageManifest manifest = 3;</code>
       * @return The manifest.
       */
      public qhx.proto.weve.update.Manifest.PackageManifest getManifest() {
        if (manifestBuilder_ == null) {
          return manifest_ == null ? qhx.proto.weve.update.Manifest.PackageManifest.getDefaultInstance() : manifest_;
        } else {
          return manifestBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 清单（包与包中文件元数据）
       * </pre>
       *
       * <code>.qhx.proto.weve.update.PackageManifest manifest = 3;</code>
       */
      public Builder setManifest(qhx.proto.weve.update.Manifest.PackageManifest value) {
        if (manifestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          manifest_ = value;
          onChanged();
        } else {
          manifestBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 清单（包与包中文件元数据）
       * </pre>
       *
       * <code>.qhx.proto.weve.update.PackageManifest manifest = 3;</code>
       */
      public Builder setManifest(
          qhx.proto.weve.update.Manifest.PackageManifest.Builder builderForValue) {
        if (manifestBuilder_ == null) {
          manifest_ = builderForValue.build();
          onChanged();
        } else {
          manifestBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 清单（包与包中文件元数据）
       * </pre>
       *
       * <code>.qhx.proto.weve.update.PackageManifest manifest = 3;</code>
       */
      public Builder mergeManifest(qhx.proto.weve.update.Manifest.PackageManifest value) {
        if (manifestBuilder_ == null) {
          if (manifest_ != null) {
            manifest_ =
              qhx.proto.weve.update.Manifest.PackageManifest.newBuilder(manifest_).mergeFrom(value).buildPartial();
          } else {
            manifest_ = value;
          }
          onChanged();
        } else {
          manifestBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 清单（包与包中文件元数据）
       * </pre>
       *
       * <code>.qhx.proto.weve.update.PackageManifest manifest = 3;</code>
       */
      public Builder clearManifest() {
        if (manifestBuilder_ == null) {
          manifest_ = null;
          onChanged();
        } else {
          manifest_ = null;
          manifestBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 清单（包与包中文件元数据）
       * </pre>
       *
       * <code>.qhx.proto.weve.update.PackageManifest manifest = 3;</code>
       */
      public qhx.proto.weve.update.Manifest.PackageManifest.Builder getManifestBuilder() {
        
        onChanged();
        return getManifestFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 清单（包与包中文件元数据）
       * </pre>
       *
       * <code>.qhx.proto.weve.update.PackageManifest manifest = 3;</code>
       */
      public qhx.proto.weve.update.Manifest.PackageManifestOrBuilder getManifestOrBuilder() {
        if (manifestBuilder_ != null) {
          return manifestBuilder_.getMessageOrBuilder();
        } else {
          return manifest_ == null ?
              qhx.proto.weve.update.Manifest.PackageManifest.getDefaultInstance() : manifest_;
        }
      }
      /**
       * <pre>
       * 清单（包与包中文件元数据）
       * </pre>
       *
       * <code>.qhx.proto.weve.update.PackageManifest manifest = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          qhx.proto.weve.update.Manifest.PackageManifest, qhx.proto.weve.update.Manifest.PackageManifest.Builder, qhx.proto.weve.update.Manifest.PackageManifestOrBuilder> 
          getManifestFieldBuilder() {
        if (manifestBuilder_ == null) {
          manifestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              qhx.proto.weve.update.Manifest.PackageManifest, qhx.proto.weve.update.Manifest.PackageManifest.Builder, qhx.proto.weve.update.Manifest.PackageManifestOrBuilder>(
                  getManifest(),
                  getParentForChildren(),
                  isClean());
          manifest_ = null;
        }
        return manifestBuilder_;
      }

      /**
       * <pre>
       * 包：URI 方式
       * </pre>
       *
       * <code>string package_uri = 4;</code>
       * @return Whether the packageUri field is set.
       */
      @java.lang.Override
      public boolean hasPackageUri() {
        return packageCase_ == 4;
      }
      /**
       * <pre>
       * 包：URI 方式
       * </pre>
       *
       * <code>string package_uri = 4;</code>
       * @return The packageUri.
       */
      @java.lang.Override
      public java.lang.String getPackageUri() {
        java.lang.Object ref = "";
        if (packageCase_ == 4) {
          ref = package_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (packageCase_ == 4) {
            package_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 包：URI 方式
       * </pre>
       *
       * <code>string package_uri = 4;</code>
       * @return The bytes for packageUri.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getPackageUriBytes() {
        java.lang.Object ref = "";
        if (packageCase_ == 4) {
          ref = package_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (packageCase_ == 4) {
            package_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 包：URI 方式
       * </pre>
       *
       * <code>string package_uri = 4;</code>
       * @param value The packageUri to set.
       * @return This builder for chaining.
       */
      public Builder setPackageUri(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  packageCase_ = 4;
        package_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 包：URI 方式
       * </pre>
       *
       * <code>string package_uri = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPackageUri() {
        if (packageCase_ == 4) {
          packageCase_ = 0;
          package_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * 包：URI 方式
       * </pre>
       *
       * <code>string package_uri = 4;</code>
       * @param value The bytes for packageUri to set.
       * @return This builder for chaining.
       */
      public Builder setPackageUriBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        packageCase_ = 4;
        package_ = value;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * 包：命令直接携带方式
       * </pre>
       *
       * <code>bytes package_raw = 5;</code>
       * @return Whether the packageRaw field is set.
       */
      public boolean hasPackageRaw() {
        return packageCase_ == 5;
      }
      /**
       * <pre>
       * 包：命令直接携带方式
       * </pre>
       *
       * <code>bytes package_raw = 5;</code>
       * @return The packageRaw.
       */
      public com.google.protobuf.ByteString getPackageRaw() {
        if (packageCase_ == 5) {
          return (com.google.protobuf.ByteString) package_;
        }
        return com.google.protobuf.ByteString.EMPTY;
      }
      /**
       * <pre>
       * 包：命令直接携带方式
       * </pre>
       *
       * <code>bytes package_raw = 5;</code>
       * @param value The packageRaw to set.
       * @return This builder for chaining.
       */
      public Builder setPackageRaw(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  packageCase_ = 5;
        package_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 包：命令直接携带方式
       * </pre>
       *
       * <code>bytes package_raw = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPackageRaw() {
        if (packageCase_ == 5) {
          packageCase_ = 0;
          package_ = null;
          onChanged();
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:qhx.proto.weve.update.Command)
    }

    // @@protoc_insertion_point(class_scope:qhx.proto.weve.update.Command)
    private static final qhx.proto.weve.update.CommandOuterClass.Command DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new qhx.proto.weve.update.CommandOuterClass.Command();
    }

    public static qhx.proto.weve.update.CommandOuterClass.Command getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Command>
        PARSER = new com.google.protobuf.AbstractParser<Command>() {
      @java.lang.Override
      public Command parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Command(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Command> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Command> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public qhx.proto.weve.update.CommandOuterClass.Command getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_qhx_proto_weve_update_Command_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_qhx_proto_weve_update_Command_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcommand.proto\022\025qhx.proto.weve.update\032\016" +
      "manifest.proto\"\277\001\n\007Command\0220\n\004type\030\001 \001(\016" +
      "2\".qhx.proto.weve.update.CommandType\022\017\n\007" +
      "options\030\002 \001(\014\0228\n\010manifest\030\003 \001(\0132&.qhx.pr" +
      "oto.weve.update.PackageManifest\022\025\n\013packa" +
      "ge_uri\030\004 \001(\tH\000\022\025\n\013package_raw\030\005 \001(\014H\000B\t\n" +
      "\007package*H\n\013CommandType\022\030\n\024COMMAND_TYPE_" +
      "UNKNOWN\020\000\022\037\n\033COMMAND_TYPE_UPDATE_REQUEST" +
      "\020\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          qhx.proto.weve.update.Manifest.getDescriptor(),
        });
    internal_static_qhx_proto_weve_update_Command_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_qhx_proto_weve_update_Command_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_qhx_proto_weve_update_Command_descriptor,
        new java.lang.String[] { "Type", "Options", "Manifest", "PackageUri", "PackageRaw", "Package", });
    qhx.proto.weve.update.Manifest.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
