apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: default-pubsub
  namespace: default
spec:
  type: pubsub.jetstream
  version: v1
  metadata:
    - name: natsURL
      value: "nats://qhx:qhx@192.168.30.103:4222"
    - name: durableName
      value: a-consumer
    - name: deliverAll
      value: true